### ISSUE TITLE
Special characters

### ISSUE THREAD

**Issue by npilorge** [spikeydragoon/Cross-Ark-Chat#1]
Hi spikeydragoon,

I'm french and I use your solution for my ark server and my discord :) Thank you for your solution. it's realy pratical ! I meet some problems and I want to talk about with you. 

Special characters of general channel in ark don't working correctly in channel discord 
In French, if I write "ah j'ai une idée" in game, in the discord I say "ah j'ai une id?e"
I think it is a problem with rcon but I don't know =x

Sorry for my poor english I don't speak very well :p

**Comment by spikeydragoon** [comment]
Yes RCON doesn't support Unicode sadly which is why it does that. If wildcard ever adds Unicode support to RCON my bot already supports Unicode and will work.

**Comment by strikepredator** [comment]
Actually, there is a plugin that you can add using the ARK Api, that adds unicode functionality to ARK.
The link to it is here: https://arkserverapi.com/resources/unicode-rcon.17/

**Comment by strikepredator** [comment]
The tutorial on how to install the ARK Api for your server to run plugins is here: https://arkserverapi.com/resources/ark-server-api.4/

**Comment by spikeydragoon** [comment]
This is a half way fix and not usable by everyone which is why i never posted it.

**Comment by spikeydragoon** [comment]
After the high request for this i have added it into new version 3.3.

I still wont build the list myself however in the wordfilter.json file there is a section called wordreplacementlist that you can add the old letter/word and bot will replace it with the the new letter/word.

This will allow the above to happen you just would build your own custom list so you would have more control over what you want replaced.
