### ISSUE TITLE
Cross-Ark-Chat v3.2.0.0 wont start

### ISSUE THREAD

**Issue by Markezzz** [spikeydragoon/Cross-Ark-Chat#10]
Hello all,

i wanted to update the Cross-Ark-Chat today to the new version with new configs.
But it wont start the bot and i get the followed error:

https://pastebin.com/BPbp53Z1

This is my new config:

https://pastebin.com/8Pu72228

I use Windows Server 2012 Standard as os. Their is no log or anything what would me help.
So i need some help to get it to work. The old versions of Cross-Ark-Chat all working for me.

Greetz,
Markezzz

**Comment by spikeydragoon** [comment]
Its complaining about adding stuff from the config to the code. I checked your config and you added to many , which broke the formatting.

In the Servers section of your config remove the , after all the ServerchannelId and you will be good to go.

**Comment by spikeydragoon** [comment]
Thats usally due to formatting can you resend the config that you changed?

**Comment by Markezzz** [comment]
Here is my current test configuration: https://pastebin.com/FLh6EdKN

**Comment by spikeydragoon** [comment]
Okay formatting is fixed only issue i see is you told bot to send server chat to its own channel but the servers have the exact same channel id. This causes errors. IF your sending them to the same channel just set the DiscordChannelID and set the sendtoown channel back to false This will send all servers chat to the DiscordChannelID.

**Comment by Markezzz** [comment]
Thanks, we found the mistake. i copy pasted all and forgot to set the channel ids for every other server. :)
Now it starts without any error. 👍

**Comment by spikeydragoon** [comment]
Good to hear :)
