### ISSUE TITLE
Player counter not working..

### ISSUE THREAD

**Issue by strikepredator** [spikeydragoon/Cross-Ark-Chat#13]
![image](https://user-images.githubusercontent.com/37594687/48969746-5071bf00-f003-11e8-886c-5701b7a36537.png)

**Comment by spikeydragoon** [comment]
I would try restarting the bot if still having a problem it could be steam not pulling info. Things to check would be does the bot console say patch every so often thats it updating the channel description. If you dont see that then its either stopped or its not getting info from steam.

**Comment by strikepredator** [comment]
I will be testing that and will close the issue if I deem it resolved. I have experienced this on several versions of the bot. Why does it hang up after a while?

**Comment by strikepredator** [comment]
That would be cool if it restarts. My only issue is that it should check what it already posted in Discord and what is new so that I don't miss out on messages when it restarts.

I am also running the bot on my own server, where the ark servers are located. It works fine sometimes for a long periods of time but sometimes it does not.

**Comment by spikeydragoon** [comment]
Is that after a manual restart or running the restartchat or reboot command?

**Comment by strikepredator** [comment]
That is after manual restart, basically closing and reopening the window. I didn't even know there was a reboot command. What is the command exactly?

**Comment by spikeydragoon** [comment]
reboot :P but to see all commands you have permissions for just run d!help just make sure you set up the discord role name file or when you run help you wont see any commands.

**Comment by spikeydragoon** [comment]
Well looks like its just steam db checked mine and numbers are way off so i will be swapping the system back over to rcon to prevent this from happening again.

Add to to-do list.
https://github.com/spikeydragoon/Cross-Ark-Chat/projects/1

Side note not sure if this is just a one time steam thing but overall just better to swap it to rcon.

**Comment by strikepredator** [comment]
Thank you, that should fix it! Do you have a Discord Server? I wanna keep in touch because I will be making a video on the bot or even offer hosting for it with your blessing!

**Comment by spikeydragoon** [comment]
Yeah thought you was on there at one point but here is link.
https://discord.gg/HAk4BmN

**Comment by strikepredator** [comment]
Thx, yeah deleted some servers..
