### ISSUE TITLE
"Failed with result 'start-limit-hit'."

### ISSUE THREAD

**Issue by TeH-BaK** [spikeydragoon/Cross-Ark-Chat#18]
Hi, i'm having issues starting the service, i'm getting the following back when running command
`sh-4.3$ sudo systemctl status CrossArkChat.service`

```
\u25cf CrossArkChat.service - ARK Cross Chat Service
   Loaded: loaded (/lib/systemd/system/CrossArkChat.service; enabled; vendor preset: enabled)
   Active: failed (Result: start-limit-hit) since Thu 2019-04-18 16:28:33 BST; 27s ago
  Process: 6905 ExecStop=/usr/bin/killall -TERM srcds_linux (code=exited, status=1/FAILURE)
  Process: 6903 ExecStart=/home/desktop/CrossArkChat/CrossArkChat (code=exited, status=203/EXEC)
 Main PID: 6903 (code=exited, status=203/EXEC)

Apr 18 16:28:28 ns300658 systemd[1]: CrossArkChat.service: Unit entered failed state.
Apr 18 16:28:28 ns300658 systemd[1]: CrossArkChat.service: Failed with result 'exit-code'.
Apr 18 16:28:33 ns300658 systemd[1]: CrossArkChat.service: Service hold-off time over, scheduling restart.
Apr 18 16:28:33 ns300658 systemd[1]: Stopped ARK Cross Chat Service.
Apr 18 16:28:33 ns300658 systemd[1]: CrossArkChat.service: Start request repeated too quickly.
Apr 18 16:28:33 ns300658 systemd[1]: Failed to start ARK Cross Chat Service.
Apr 18 16:28:33 ns300658 systemd[1]: CrossArkChat.service: Unit entered failed state.
Apr 18 16:28:33 ns300658 systemd[1]: CrossArkChat.service: Failed with result 'start-limit-hit'.
```
I'm afraid though i'm technically minded, i'm not overly comfortable on linux, and i'm quite lost as to how to approach this issue. I have double check and fixed some syntax issues in the config, and i think it looks clean now. Any ideas?

Thanks in advance!

**Comment by spikeydragoon** [comment]
Biggest things to check is make sure the chmod settings is correct and that the bots config file is good. That error is from it trying to start the program multi times but its crashing for whatever reason being either permissions issue or program itself crashing.

To help can you post your config here just delete the password and the discord bot token and i can take a look to see whats going on.

**Comment by TeH-BaK** [comment]
My censored config:
https://pastebin.com/eVdnuFkk

With the installation I followed the instructions by the letter. So I'm hoping its something amiss in the config, else that might end up being a bit of a headache for me!

Thanks for looking :)

**Comment by spikeydragoon** [comment]
"SendJoinLeaveNotificationsToServerOwnChannel": true should be set to false.

Everything else looks good. Only thing to note is if this is a server you own yourself you should use your lan ip instead of public ip.

**Comment by TeH-BaK** [comment]
Thanks, i'll set that, and give it a try shortly.

Hosted dedicated datacentre machine, I'll try find out the LAN IP, I take it that I can't just use a 'localhost' equivalent like on windoze?

**Comment by spikeydragoon** [comment]
You can use localhost but if its in a datacenter that public ip is fine to use in most cases.

**Comment by TeH-BaK** [comment]
Just changing that one setting seems to result in the same thing.

```
sh-4.3$ sudo systemctl start CrossArkChat.service
sh-4.3$ sudo systemctl status CrossArkChat.service
\u25cf CrossArkChat.service - ARK Cross Chat Service
   Loaded: loaded (/lib/systemd/system/CrossArkChat.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2019-04-18 18:17:45 BST; 2s ago
  Process: 19620 ExecStop=/usr/bin/killall -TERM srcds_linux (code=exited, status=1/FAILURE)
  Process: 19618 ExecStart=/home/desktop/CrossArkChat/CrossArkChat (code=exited, status=203/EXEC)
 Main PID: 19618 (code=exited, status=203/EXEC)

Apr 18 18:17:45 ns300658 systemd[1]: CrossArkChat.service: Failed with result 'exit-code'.
sh-4.3$ sudo systemctl status CrossArkChat.service
\u25cf CrossArkChat.service - ARK Cross Chat Service
   Loaded: loaded (/lib/systemd/system/CrossArkChat.service; enabled; vendor preset: enabled)
   Active: failed (Result: start-limit-hit) since Thu 2019-04-18 18:18:00 BST; 38s ago
  Process: 20084 ExecStop=/usr/bin/killall -TERM srcds_linux (code=exited, status=1/FAILURE)
  Process: 20082 ExecStart=/home/desktop/CrossArkChat/CrossArkChat (code=exited, status=203/EXEC)
 Main PID: 20082 (code=exited, status=203/EXEC)

Apr 18 18:17:55 ns300658 systemd[1]: CrossArkChat.service: Unit entered failed state.
Apr 18 18:17:55 ns300658 systemd[1]: CrossArkChat.service: Failed with result 'exit-code'.
Apr 18 18:18:00 ns300658 systemd[1]: CrossArkChat.service: Service hold-off time over, scheduling restart.
Apr 18 18:18:00 ns300658 systemd[1]: Stopped ARK Cross Chat Service.
Apr 18 18:18:00 ns300658 systemd[1]: CrossArkChat.service: Start request repeated too quickly.
Apr 18 18:18:00 ns300658 systemd[1]: Failed to start ARK Cross Chat Service.
Apr 18 18:18:00 ns300658 systemd[1]: CrossArkChat.service: Unit entered failed state.
Apr 18 18:18:00 ns300658 systemd[1]: CrossArkChat.service: Failed with result 'start-limit-hit'.
```

So i can use 
`"IP": "localhost",`
instead of the IP?

**Comment by TeH-BaK** [comment]
I wasn't sure about using a domain, so I tried "127.0.0.1" - same issue. I guess its time to look into the permissions.

**Comment by TeH-BaK** [comment]
I've ran the chmod settings again, I've even ran through all the setup again, making sure I missed nothing. Each time i changed anything i did the following:
```> sh-4.3$ sudo systemctl stop CrossArkChat.service
> sh-4.3$ sudo systemctl daemon-reload
> sh-4.3$ sudo systemctl start CrossArkChat.service
> sh-4.3$ sudo systemctl status CrossArkChat.service```

I also found in the system service settings a possible problem, it specifys:
`ExecStart=/home/<your-username>/CrossArkChat/CrossArkChat`
when for me it seems to be installed to
`ExecStart=/home/CrossArkChat/CrossArkChat`
I tried both variations, (obviously with my username in there), neither seemed to affect the outcome.

So I think i'm out of ideas now.

**Comment by spikeydragoon** [comment]
Not sure myself i dont use linux to often and perseus made that guide for me. If you join the discord and ask maybe someone who uses linux frequently would know.

**Comment by TeH-BaK** [comment]
Just an FYI. This was never resolved.
If you could add some further debugging to the project maybe that could help resolve this and other similar issues, otherwise the issue is so vague that I fear to use this project for the likelihood of further issues at a later date that could be next to impossible to diagnose... Let alone my issue of just getting it working in the first place.
I expect the windows version might be another story. A real shame, this project I had such high hopes for.

**Comment by spikeydragoon** [comment]
In terms of the program itself nothing is wrong so the issues your having is related to linux so not much i can really provide help wise there since i rarely use it.

Only thing i can really say do is instead of running it like a service above try just launching the program itself that way you can see the errors which would provide more info. The way your running it now errors are to generic for me to help but googling it most are saying its more on linux side issue.

Just cd into the file with the crossarkchat file and run it via console sudo ./CrossArkChat that would give us info on if its the program itself having the problems or something with the way linux is trying to run it.

**Comment by TeH-BaK** [comment]
Sounds like a plan, I'll try that a bit later and let you know what it comes up with. Thanks again!

**Comment by spikeydragoon** [comment]
Np for now i re opened until we find out for sure program is not at fault.

**Comment by TeH-BaK** [comment]
Seems it was a very simple problem, the configs were in the main directory, but should have been in the configs folder.

Either something uniquely went wrong during extraction for me, or that should maybe added to the installation guide?

Thanks for your patience in helping me resolve this, hopefully the rest of the configuring to precisely how I want it will be uneventful!

**Comment by spikeydragoon** [comment]
Since they are in there by default since thats how its shipped i dont think the guide covers that but yeah i can add a note to it saying to make sure.

Once your running 100% make sure to mark this closed thank you for following up with the solution.

**Comment by TeH-BaK** [comment]
Other than the aforementioned directory discrepancy in the service, which I reconfigured, it's now fully started as a service. Thanks again :)

**Comment by TeH-BaK** [comment]
I'm very pleased to say, messages seem to be working perfectly now. :D
