### ISSUE TITLE
Error : Segmentation fault

### ISSUE THREAD

**Issue by Al3601** [spikeydragoon/Cross-Ark-Chat#2]
Hi, 

first thank you for this awesome Bot, but i cannot get it work, i followed the readme word by word, when i try to execute ./CrossDiscordArkChat  (permission for all the folder changed to 755), i get the message 'Segmentation fault'.

what cause this error ? google say it is a memory lake problem, i have 10/32 go free....

Debian 9.4 / CrossDiscordChat

**Comment by spikeydragoon** [comment]
Not sure if everything was installed it should work i tested it on Ubuntu and centos personally.

If you join the discord server i can offer faster support.

**Comment by spikeydragoon** [comment]
closing due to no reply from op.

**Comment by Al3601** [comment]
@spikeydragoon 
Hi , thank you, couples of months after the first error , here is what i get now with the last version

`:~/arkservers/ARK-apps/CrossArkChat$ ./CrossArkChat
CrossArkChat
Version 3.2.0.0
This program was created by Spikeydragoon and is intended for free use.
If you paid for this program you have been scammed.
Thanks to 'sowa' for creating the application icon.

04:45:08 [Info] Discord: Discord.Net v2.0.0-beta (API v6)

Unhandled Exception: Discord.Net.HttpException: The server responded with error 401: 401: Unauthorized
   at Discord.Net.Queue.RequestBucket.<SendAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Net.Queue.RequestQueue.<SendAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.API.DiscordRestApiClient.<SendInternalAsync>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.API.DiscordRestApiClient.<SendAsync>d__57`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.API.DiscordRestApiClient.<GetVoiceRegionsAsync>d__142.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.WebSocket.DiscordSocketClient.<OnLoginAsync>d__86.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Rest.BaseDiscordClient.<LoginInternalAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.Rest.BaseDiscordClient.<LoginInternalAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Rest.BaseDiscordClient.<LoginAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CrossArkChat.DiscordStartupService.<StartAsync>d__4.MoveNext() in C:\Development\Open Source\CrossArkChat\Main\CrossArkChat\Services\DiscordStartupService.cs:line 63
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CrossArkChat.Program.<StartAsync>d__2.MoveNext() in C:\Development\Open Source\CrossArkChat\Main\CrossArkChat\Program.cs:line 147
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CrossArkChat.Program.Main(String[] args) in C:\Development\Open Source\CrossArkChat\Main\CrossArkChat\Program.cs:line 15
Aborted

`
Debian 9.5

**Comment by spikeydragoon** [comment]
Unhandled Exception: Discord.Net.HttpException: The server responded with error 401: 401: Unauthorized
at Discord.Net.Queue.RequestBucket.d__18.MoveNext()

Means its not liking your token or something changed bot account wise so make sure you entered it all right and that you didnt remove anything by mistake in config formating

**Comment by spikeydragoon** [comment]
I was told the prefixs stopped working in 3.2 so just use 3.1 for now i have fixed it already however im waiting to release it while i finish the planned updates to release them at 1 time.
Bug tracking is here. https://github.com/spikeydragoon/Cross-Ark-Chat/projects/1

**Comment by Al3601** [comment]
ok, i can't download the 3.1 the link is broken (404) 

https://www.dropbox.com/s/7ejivgtlfpd38xu/CrossDiscordArkChat.zip?dl=0

i'll wait for the next release. thank you

**Comment by spikeydragoon** [comment]
You can also ask in discord server someone might have old one.

**Comment by spikeydragoon** [comment]
This has been fixed in v3.3 thats now available for download.

**Comment by Al3601** [comment]
@spikeydragoon 

just tested right now, here what i cannot get to work:

/help  message  // ingame not send any message to Admin role and not logged in the specified Disord channel
/d! !rules      // in discord i got  UnknownCommand: Unknown command.

The big problem is that i cannot get the TribLogs in the specified Discord channels (i want my Trib logs get logged in our own channel tribe etc...)

now i the tribe logs goes to the general chat... what is the corrrect config for this ?

**Comment by spikeydragoon** [comment]
The game commands are only usable in game doesnt work in discord which is why its saying an unknown command.

How is your new config set up?

**Comment by Al3601** [comment]
"Servers": [
    {
      "Map": "ragnarok",
      "IP": "XXX.XXX.XX.XX",
      "RconPort": 32333,
      "QueryPort": 27014,
      "Password": "XXXXX",
      "Prefix": "/ragnarok",
      "Active": true,
      "ServerChannelId": 407351142658473985
    },
    {
      "Map": "ragnarokTEK",
      "IP": "XXX.XXX.XX.XX",
      "RconPort": 32334,
      "QueryPort": 27015,
      "Password": "XXXXX",
      "Prefix": "/ragnarokTEK",
      "Active": true,
      "ServerChannelId": 392021756191178752
    }
  ],

  "TribeIDs": [
    {
      "TribeId": "1731500039",
      "Active": true,
      "TribeDiscordId": 453786094329397259
    },
    {
      "TribeId": "00000",
      "Active": false,
      "TribeDiscordId": 0
    }
  ],

  "GameCommands": [
    {
      "Command": "!discord",
      "CommandReply": "https://discord.gg/XXXX",
      "Active": true
    },
    {
      "Command": "!rules",
      "CommandReply": "These are the rules.",
      "Active": true
    },
    {
      "Command": "!ping",
      "CommandReply": "Pong!",
      "Active": true
    }
  ],

  "CustomTagList": [
    "ACM[CMD]",
    "SERVER: ACM[CMD]"
  ],

  "ChatSettings": {
    "ShowAdminCommands": true,
    "SendAdminCommandsToOwnChannel": true,
    "ShowTribelogsInChat": true,
    "UsePrefixToSendChat": false,
    "UseCustomTags": false,
    "LogChat": true,
    "LogAdminCommands": true,
    "LogTribeLogs": false,
    "UseGameCommands": true,
    "PrefixToSendAllServers": "/all"
  },

  "DiscordSettings": {
    "DiscordChannelID": 453789802920411136,
    "TribeLogsDiscordChannelID": 508494801562501136,
    "AdminCommandsDiscordChannelID": 508703491536191498,
    "SupportChannelID": 508495027526434816,
    "JoinLeaveNotificationsDiscordChannelID": 509435837516349453,
    "prefix": "d!",
    "DiscordChatPrefix": "Discord",
    "DiscordToken": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "ShowChatPrefixInDiscord": true,
    "SendTribeLogsToOwnChannel": true,
    "SendServerChatToOwnChannel": true,
    "UseSupportPrefix": true,
    "UseJoinLeaveNotifications": true,
    "SendJoinLeaveNotificationsToServerOwnChannel": true,
    "UseWordReplacementList": false,
    "PingRoleName": true,
    "ReplyToSupportPing": true,
    "SendChatToDiscord": true,
    "SupportPrefix": "/help",
    "PrefixToSendToDiscord": "/discord",
    "SupportRoleToPing": "Admin",
    "SupportPingReply": "Your support ticket has been sent."
  }


Thanks for your help

**Comment by spikeydragoon** [comment]
The way you have it set all server chat will go to its own discord channel and a copy will show up in the DiscordChannelID.

For tribe logs all logs will go to TribeLogsDiscordChannelID unless it sees a tribe log matching the tribe id of 1731500039 at which it would then send it to 453786094329397259 instead.

Admin commands should go to 508703491536191498 with send to own channel enabled.

Does it do any of that or show up in console?

**Comment by Al3601** [comment]
here what happens with this config:

tribelogs goes to "DiscordChannelID": 453789802920411136, and here "ServerChannelId": 407351142658473985 
I want them to go to "TribeLogsDiscordChannelID": 508494801562501136, (for all tribes) and here  "TribeDiscordId": 453786094329397259 (for my own tribe)

Admin commands are not show up in the console & no show in the specified channel.
the "/help message"  show in the console and not in the discord channel 508495027526434816

**Comment by spikeydragoon** [comment]
That means for some reason its not getting flagged as a tribe log. Can you send me a shot of one of the tribe logs so i can see if they changed the tag or not.

**Comment by Al3601** [comment]
ahh do i need to set " culture=fr" to "culture=en" to get this working correctly ? or you can make this configurable in _configuration.json?

**Comment by spikeydragoon** [comment]
I can make it set able in the config but for testing to make sure thats what it is i want to send a hardcoded version with the change unless you can temp set it to en to see if that fixes it which ever is easier on you.

**Comment by Al3601** [comment]
ok im going to test it right now by converting the server to EN

**Comment by spikeydragoon** [comment]
Sounds good let me know the results.

**Comment by Al3601** [comment]
i can confirm all working good now since i converted the server to "culture=en"

except "/help need admin" no log into discord and no alert to admin role
!rules or !discord not working ingame

**Comment by spikeydragoon** [comment]
Added the config change for the culture to the to-do list https://github.com/spikeydragoon/Cross-Ark-Chat/projects/1

As far as the game commands and support command are they even showing up in the console?

**Comment by Al3601** [comment]
during my tests here is the results with 2 server converted to EN:

/help admin i need help   //show in the console, not in discord.
!rules      //no logs on the console or Discord
!discord   //no logs on the console or Discord
d! !rules   // if i message the BOT direcly on discord i get  "UnknownCommand: Unknown command."
d! !discord   // if i message the BOT direcly on discord i get  "UnknownCommand: Unknown command."

**Comment by spikeydragoon** [comment]
K ill test game commands in a bit to see whats causing them to not work.

Running the game commands in discord is suppose to show unknown as they dont work in discord only in-game.

**Comment by spikeydragoon** [comment]
Okay found issue with game commands and is fixed will add in version 3.4

**Comment by Al3601** [comment]
oh that was quick thank you!

**Comment by Al3601** [comment]
a little feedback from lastest version 3.4.0.0 
ingame commands work like charm!
/help command generate an error in RconErrros.txt

02:01:13_System.NullReferenceException: Object reference not set to an instance of an object.
   at CrossArkChat.CrossArkChatService.<SendSupportDiscordMessageAsync>d__36.MoveNext() in C:\Development\Open Source\CrossArkChat\Main\CrossArkChat\Services\CrossArkChatService.cs:line 1006

**Comment by spikeydragoon** [comment]
Just tested on my server and its working what are your settings for it?

**Comment by spikeydragoon** [comment]
It might be since the reply goes to ark which doesn't have UTF-8 for testing just change it to aci character and see what happens

**Comment by Al3601** [comment]
hello, tested  today same problem:

09:02:22_System.NullReferenceException: Object reference not set to an instance of an object.
   at CrossArkChat.CrossArkChatService.<SendSupportDiscordMessageAsync>d__36.MoveNext() in C:\Development\Open Source\CrossArkChat\Main\CrossArkChat\Services\CrossArkChatService.cs:line 1006

**Comment by spikeydragoon** [comment]
As i said before that is more of a warning not an error. Its just letting you know server didnt reply with any data. Doesnt say the reason so it doesnt mean its a problem.

Just looking at the config everything looks right so without seeing everything in person i cant say whats causing it to do that. I have tested on 3.4 on multi servers/os and they are all working properly so its something on either the server side or config side that im just not seeing.

One thing i have ran into is some languages mess with the config so to make sure that isnt a problem Use notepad++ and set it to english then edit a new config with it to see if that makes a difference past that im  out of ideas without doing it myself.
