### ISSUE TITLE
I want to keep the game from showing up on the chat when I write the command

### ISSUE THREAD

**Issue by MinTo0831** [spikeydragoon/Cross-Ark-Chat#20]
I want to keep the game from showing up on the chat when I write the command

Is there a way?

ex) A3 (User name ABCD, Arc ID: 123456789, Steam ID: 123465789456123)

And

: Discord: A4(NAME): DADAD
: A4 : DADWD

: Discord: <<<<<
Discord: <<<<<Can’t you change this?

**Comment by spikeydragoon** [comment]
If you mean admin commands from in-game yes you just set show admin commands to false in the config and it wont show them in chat.

**Comment by spikeydragoon** [comment]
Just realized didn't reply to second part of question. Yes you can change the word discord in the config as well or hide it.

**Comment by MinTo0831** [comment]
> Just realized didn't reply to second part of question. Yes you can change the word discord in the config as well or hide it.

What parts can you modify?

I can't see
I can't see it anymore

I can still see it in the discodes.

Where should I modify?
Let me know.

**Comment by spikeydragoon** [comment]
You should look over the wiki page as it goes over every setting in all the configs.
This is the link directly to just the config.json file.
https://github.com/spikeydragoon/Cross-Ark-Chat/wiki/Configuration-for-_configuration.json
"DiscordChatPrefix": "Discord", is the one you change to change the name.
