### ISSUE TITLE
Homepage Chat

### ISSUE THREAD

**Issue by Vakarian96** [spikeydragoon/Cross-Ark-Chat#21]
Hello,

sorry my english isn't so good.

We want the ARK chat also on our homepage showing and that members can take notes.

We have created a bot and send all messages from the homepage and the ARKs to a Discord Channel. Everything works wonderfully, the chat of ARK appears with us on the homepage.

Now to the problem:
Messages sent via the homepage are only sent if the setting IgnoreOtherBots is set to false.

In addition there is now the problem, if someone writes something on an ARK server, the message is sent twice. 

https://data.sponsor-universe.eu/index.php/s/wcMdfToWsefE6o7

Is there a solution?

With kind regards,
Vakarian

**Comment by spikeydragoon** [comment]
Hello,

For first problem IgnoreOtherBots must be false for it to read from other programs. With it set to true it will only read what normal users write.

For second problem i see the issue i forgot to tell the bot to ignore itself so it wont send twice. I will have to fix that in next update.

I already coded the fix i just have to push it out, will be out shortly.

**Comment by spikeydragoon** [comment]
@Vakarian96 Okay new version is pushed should fix your problem. Download v5.8 from the release page, it uses the same config so just copy the old 5.7 config file over to keep from retyping your settings.

Let me know if that fixed it for you.

**Comment by Vakarian96** [comment]
Thanks, it's working perfectly.
![chat2](https://user-images.githubusercontent.com/19644488/61187262-b634b900-a66f-11e9-949a-2c96e1ced6b0.PNG)
![chat1](https://user-images.githubusercontent.com/19644488/61187263-b634b900-a66f-11e9-94c4-be4f43fba522.PNG)

**Comment by spikeydragoon** [comment]
Awesome closing ticket then.
