### ISSUE TITLE
Configured 

### ISSUE THREAD

**Issue by Appelkiller** [spikeydragoon/Cross-Ark-Chat#29]
Dear Spikeydragoon,

I have recently set up an Ark server cluster with 4 different maps on HostHavoc and would love to include the cross-ark-chat to improve the communication between the maps and the Discord server.
I have been trying to configure the _configuration.json file as described on your wiki.
After adding in all the data of the cluster to each cluster configuration file (IPs, RCOns, passwords and Discord connections), the cross ark chat and Discord app still do not not work. We do not get any error messages either.
I have tried to read the description and coding several times but am still not sure what I need to change to get it to work. 
Below this message, I have included the current _configuration.json file without the passwords, Discord bot token and channel code.

I hope you can help me fix this problem.

Kind regards,

Patrick

//For all info on config visit https://github.com/spikeydragoon/Cross-Ark-Chat and look at the readme file as it goes over all config information.
// DO NOT change anything in the Rcon settings unless you know what you are doing!!!
{
  "ApplicationSettings": {
    "VersionCheckUrl": "https://raw.githubusercontent.com/spikeydragoon/Cross-Ark-Chat/master/version.txt",
    "PatchNotesCheckUrl": "https://raw.githubusercontent.com/spikeydragoon/Cross-Ark-Chat/master/CrossArkChatPatchNotes.txt",
    "LogErrors": true,
    "LogChat": true,
    "LogAdminCommands": true,
    "LogTribeLogs": true,
    "UseDiscord": true,
    "DiscordLogSeverity": "info"
  },

  "Servers": [
    {
      "NameTag": "Aberration",
      "IP": "173.234.27.85",
      "RconPort": 27060,
      "QueryPort": 27059,
      "Password": "Removed the info for privacy",
      "SettingToUse": 1,
      "Active": true
    }, 
    {
      "NameTag": "Extinction",
      "IP": "173.234.27.85",
      "RconPort": 27063,
      "QueryPort": 27062,
      "Password": "Removed the info for privacy",
      "SettingToUse": 2,
      "Active": true
    },
    {
      "NameTag": "Ragnarok",
      "IP": "173.234.27.85",
      "RconPort": 27051,
      "QueryPort": 27050,
      "Password": "Removed the info for privacy",
      "SettingToUse": 3,
      "Active": true
    },
    {
      "NameTag": "TheCenter",
      "IP": "173.234.27.85",
      "RconPort": 27069,
      "QueryPort": 27068,
      "Password": "Removed the info for privacy",
      "SettingToUse": 4,
      "Active": true
    }
  ],

  "ServerSettings": [
    {
      "SettingNumber": 1,
      "ServerTag": "Aberration",
      "ServerPlayerTag": ":",
      "PlayerChatTag": ":",
      "ChatTag": "",
      "HideNameTag": false,
      "DiscordChannelId": Removed the info for privacy
    },
    {
      "SettingNumber": 2,
      "ServerTag": "Extinction",
      "ServerPlayerTag": ":",
      "PlayerChatTag": ":",
      "ChatTag": "",
      "HideNameTag": false,
      "DiscordChannelId": Removed the info for privacy
    },
    {
      "SettingNumber": 3,
      "ServerTag": "Ragnarok",
      "ServerPlayerTag": ":",
      "PlayerChatTag": ":",
      "ChatTag": "",
      "HideNameTag": false,
      "DiscordChannelId": Removed the info for privacy
    },
    {
      "SettingNumber": 4,
      "ServerTag": "TheCenter",
      "ServerPlayerTag": ":",
      "PlayerChatTag": ":",
      "ChatTag": "",
      "HideNameTag": false,
      "DiscordChannelId": Removed the info for privacy
    }
  ],

  "PrefixGroups": [
    {
      "ChatPrefix": "/prefix",
      "ServerList": [
        "chat1",
        "chat2"
      ]
    },
    {
      "ChatPrefix": "/prefix2",
      "ServerList": [
        "chat1",
        "chat2"
      ]
    }
  ],

  "Tribes": [
    {
      "TribeId": "00000",
      "SettingToUse": 1,
      "Active": false
    },
    {
      "TribeId": "00000",
      "SettingToUse": 2,
      "Active": false
    }
  ],

  "TribeSettings": [
    {
      "SettingNumber": 1,
      "ShowFullTribeLog": false,
      "ShowTribeName": false,
      "ShowServerName": true,
      "ShowTribeId": false,
      "EmbedTribeLog": true,
      "DiscordChannelId": 0
    },
    {
      "SettingNumber": 2,
      "ShowFullTribeLog": false,
      "ShowTribeName": false,
      "ShowServerName": true,
      "ShowTribeId": false,
      "EmbedTribeLog": true,
      "DiscordChannelId": 0
    }
  ],

  "GameCommands": [
    {
      "Command": "!discord",
      "CommandReply": "https://discord.gg/",
      "Active": false
    },
    {
      "Command": "rules",
      "CommandReply": "These are the rules.",
      "Active": false
    },
    {
      "Command": "/ping",
      "CommandReply": "Pong!",
      "Active": false
    }
  ],

  "CustomTagList": [
    "ACM[CMD]",
    "SERVER: ACM[CMD]"
  ],

  "RconSettings": {
    "NoResponceTag": "Server received, But no response!!",
    "NoPlayerTag": "No Players Connected",
    "ServerRepeatTag": "SERVER:",
    "AdminCMDTag": "AdminCmd:",
    "TribeLogTag": "Tribe",
    "GetChatCmd": "getchat",
    "ListPlayersCmd": "ListPlayers",
    "ListPlayerCheckTimeInMs": 10000,
    "GetChatTimeInMs": 1000,
    "PlayerCountCheckTimeInMs": 30000,
    "VersionCheckTimeInMs": 3600000,
    "RconSendTimeoutInMs": 3000,
    "RconReceiveTimeoutInMs": 10000,
    "RconConnectionRetrys": 1
  },

  "EmbeddedTribeLogColorSettings": [
    {
      "LogType": "killed",
      "LogColor": "ff2121",
      "RoleToPing": "none"
    },
    {
      "LogType": "demolished",
      "LogColor": "ff2121",
      "RoleToPing": "none"
    },
    {
      "LogType": "claimed",
      "LogColor": "03f413",
      "RoleToPing": "none"
    },
    {
      "LogType": "unclaimed",
      "LogColor": "ff2121",
      "RoleToPing": "none"
    },
    {
      "LogType": "tamed",
      "LogColor": "03f413",
      "RoleToPing": "none"
    },
    {
      "LogType": "destroyed",
      "LogColor": "ff7400",
      "RoleToPing": "none"
    },
    {
      "LogType": "froze",
      "LogColor": "d8ddd8",
      "RoleToPing": "none"
    },
    {
      "LogType": "downloaded",
      "LogColor": "03f413",
      "RoleToPing": "none"
    },
    {
      "LogType": "uploaded",
      "LogColor": "ff2121",
      "RoleToPing": "none"
    },
    {
      "LogType": "starved",
      "LogColor": "ff2121",
      "RoleToPing": "none"
    }
  ],

  "ChatSettings": {
    "UseCustomTags": false,
    "SendChatToServers": true,
    "ShowAdminCommands": false,
    "UseGameCommands": false,
    "UsePrefixToSendChat": false,
    "UseWordReplacementList": false,
    "AllServersChatPrefix": "/all"
  },

  "DiscordSettings": {
    "DiscordBotSettings": {
      "CommandPrefix": "d!",
      "DiscordBotToken": "Removed the info for privacy",
      "IgnoreOtherBots": true,
      "ShowDiscordNickName": true
    },

    "ServerChatSettings": {
      "ChatDiscordChannelID": 647025864118108170,
      "SendServerChatToOwnChannel": false
    },

    "DiscordChatSettings": {
      "DiscordChatPrefix": "Discord",
      "SendChatToDiscord": true,
      "UsePrefixToSendToDiscord": false,
      "PrefixToSendToDiscord": "/discord"
    },

    "NotificationSettings": {
      "VersionDiscordChannelId": 0,
      "PatchNotesDiscordChannelId": 0,
      "JoinLeaveNotificationsDiscordChannelID": 0,
      "UseVersionChecker": false,
      "UsePatchNotesChecker": false,
      "UseJoinLeaveNotifications": false,
      "UsePlayerCountChannelUpdater": false,
      "SendJoinLeaveNotificationsToServerOwnChannel": false
    },

    "AdminCommandSettings": {
      "AdminCommandsDiscordChannelID": 0,
      "SendAdminCommandsToOwnChannel": false
    },

    "TribeLogSettings": {
      "TribeLogsDiscordChannelID": 0,
      "ShowTribelogs": false,
      "ShowFullTribeLog": false,
      "ShowTribeId": true,
      "ShowTribeName": true,
      "ShowServerName": true,
      "EmbedTribeLog": true,
      "SendTribeLogsToOwnChannel": false
    },

    "SupportSettings": {
      "SupportDiscordChannelID": 0,
      "UseSupportPrefix": false,
      "PingRoleName": false,
      "ReplyToSupportPing": true,
      "SupportPrefix": "/help",
      "SupportRoleToPing": "rolename",
      "SupportPingReply": "Your support ticket has been sent."
    }
  }
}

**Comment by spikeydragoon** [comment]
@Appelkiller From what i can see in the config everything looks correct.
Things to check
1: Make sure bot has read/send messages permissions in discord.
2: Make sure you dont have any other programs getting chat. Due to how wildcard coded this only one program at a time can get chat messages.
3: Make sure bot is showing online in your discord server.
4: Make sure your using the servers admin password and not the regular join password.

That should be the main things to check. Once you check that let me know. Note for faster replys can always hit me up in our discord server for cross chat.
