### ISSUE TITLE
Messaging Users Joining/Leaving

### ISSUE THREAD

**Issue by strikepredator** [spikeydragoon/Cross-Ark-Chat#3]
The can't display if a user has left or joined the game right now. It would be really cool if the bot could display that upon setting it to "true" as an option in the _configuration.json. Hope to hear back from you Spikey! Chris.

**Comment by spikeydragoon** [comment]
I will look into this the only way im aware of is building your own list. I should have time Tuesday to do some testing.

**Comment by spikeydragoon** [comment]
Added to the to-do list so closing.

**Comment by spikeydragoon** [comment]
This has been added in the new version 3.3
