### ISSUE TITLE
[Linux ] High Ports

### ISSUE THREAD

**Issue by Vakarian96** [spikeydragoon/Cross-Ark-Chat#30]
Hello,

is it possible that the ARK chat does not work for ports over 30000 or over 40000?

With best regards,
Vakarian

**Comment by spikeydragoon** [comment]
@Vakarian96 Im not sure what the max port is for ark but for windows its around 65k
Im currently using 32k range for rcon with no issues.

**Comment by smooreace** [comment]
RCON has no port limitation beyond basic internet limitations. Which has
nothing to do with Ark at all.
