### ISSUE TITLE
Tribe chat and logs not working

### ISSUE THREAD

**Issue by RonanFinley** [spikeydragoon/Cross-Ark-Chat#31]
Hello
I installed CrossArkChat on my server recently, which it is fantastic for syncing in-game chat with the discord server. However, now I am trying to sync tribe chat and logs into their individual discord channels. I set up the config (pasted below) with channel IDs and tribe IDs (triple checked), however nothing seems to work. Chat does not sync, tribe events (creature tamed, player died) do not sync, etc. The bot does have access to those channels for posting, and definitely connecting to discord since "All" chat works great. The logs only show global chat messages, nothing more. What am I doing wrong?

I am running Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-76-generic x86_64) for both CrossArkChat and the server

The Discord settings section
```json
"DiscordSettings": {
    "DiscordBotSettings": {
      "CommandPrefix": "d!",
      "DiscordBotToken": "[Expunged]",
      "IgnoreOtherBots": false,
      "ShowDiscordNickName": true
    },
    "ServerChatSettings": {
      "ChatDiscordChannelID": 672298996034961447,
      "SendServerChatToOwnChannel": false
    },
    "DiscordChatSettings": {
      "DiscordChatPrefix": "Discord",
      "SendChatToDiscord": true,
      "UsePrefixToSendToDiscord": false,
      "PrefixToSendToDiscord": "/discord"
    },
    "NotificationSettings": {
      "VersionDiscordChannelId": 0,
      "PatchNotesDiscordChannelId": 0,
      "JoinLeaveNotificationsDiscordChannelID": 0,
      "UseVersionChecker": false,
      "UsePatchNotesChecker": false,
      "UseJoinLeaveNotifications": true,
      "UsePlayerCountChannelUpdater": true,
      "SendJoinLeaveNotificationsToServerOwnChannel": false
    },
    "AdminCommandSettings": {
      "AdminCommandsDiscordChannelID": 0,
      "SendAdminCommandsToOwnChannel": false
    },
    "Tribes": [
      {
        "TribeId": "1803738692",
        "SettingToUse": "1",
        "Active": true
      },
      {
        "TribeId": "1558917733",
        "SettingToUse": "2",
        "Active": true
      }
    ],
    "TribeSettings": [
      {
        "SettingNumber": "1",
        "ShowFullTribeLog": true,
        "ShowTribeName": true,
        "ShowServerName": true,
        "ShowTribeId": true,
        "EmbedTribeLog": true,
        "DiscordChannelId": 673932033248198677
      },
      {
        "SettingNumber": "2",
        "ShowFullTribeLog": true,
        "ShowTribeName": true,
        "ShowServerName": true,
        "ShowTribeId": true,
        "EmbedTribeLog": true,
        "DiscordChannelId": 673939118014726165
      }
    ],
    "TribeLogSettings": {
      "TribeLogsDiscordChannelID": 0,
      "ShowTribelogs": true,
      "ShowFullTribeLog": true,
      "ShowTribeId": true,
      "ShowTribeName": true,
      "ShowServerName": true,
      "EmbedTribeLog": true,
      "SendTribeLogsToOwnChannel": true
    },
    "SupportSettings": {
      "SupportDiscordChannelID": 0,
      "UseSupportPrefix": false,
      "PingRoleName": false,
      "ReplyToSupportPing": true,
      "SupportPrefix": "/help",
      "SupportRoleToPing": "rolename",
      "SupportPingReply": "Your support ticket has been sent."
    }
  }```

Thanks

**Comment by spikeydragoon** [comment]
@RonanFinley Only thing i can see to change is you must have an all channel setup for all logs to go to. Currently i dont have option to disable that yet. So set it to just a channel you hide from others and you should be good to go. Also note rcon by default doesnt support tribe chat only tribe logs. So unless you have a plugin or mod that puts tribe chat in rcon you will not see chat.
 "TribeLogSettings": {
      "TribeLogsDiscordChannelID": 0,

Also make sure you have the startup pram -ServerRCONOutputTribeLogs on your server for it to output tribe logs to rcon.

**Comment by RonanFinley** [comment]
Thank you! Changing those settings made everything work wonderfully
