### ISSUE TITLE
Join and leave notifications in server chat

### ISSUE THREAD

**Issue by flagoss** [spikeydragoon/Cross-Ark-Chat#34]
Is there a way to have the join and leave notifications in the servers chat because right now we are only seeing those on discord. Thanks

**Comment by spikeydragoon** [comment]
Since ark has an option to do that i did not include that in the bot. The bot will only send it to discord currently though it has been request that i add it to chat so you can have cross server join messages, so I will look into that in the future.

**Comment by flagoss** [comment]
Thank you very much. We already use the feature included in the game. I ask about that feature because we are playing on a cluster with bases across 5 servers. It would cool to know when a friend join another server on the cluster. By the way thank you for that wonderfully software.
