### ISSUE TITLE
Support mesasges doesn't support spaces

### ISSUE THREAD

**Issue by DTSpawn** [spikeydragoon/Cross-Ark-Chat#35]
Hi there!
I'm hosting on windows server with russian localization and my problem what /sos command doesn't support spaces in it. Meaning player should send support request like this "/sos igotstuckintreeshelpmepls" otherwise Discord will not display it.

Here's my support part code
    "SupportSettings": {
      "SupportDiscordChannelID": correct-ID-here,
      "UseSupportPrefix": true,
      "PingRoleName": true,
      "ReplyToSupportPing": true,
      "SupportPrefix": "/sos",
      "SupportRoleToPing": "ArkAdmin",
      "SupportPingReply": "Ваше сообщение отправлено!"
    }

**Comment by spikeydragoon** [comment]
@DTSpawn just checked and bot is not having any problems with spaces.
command ran was
/help help message here
this shows in discord
![image](https://user-images.githubusercontent.com/29191122/77262948-279c2100-6c6d-11ea-9f96-fa351ef7c95f.png)

**Comment by DTSpawn** [comment]
Can it be because of russian localization?

**Comment by DTSpawn** [comment]
That's odd, but now it's working for me too! Let's call it Voodoo)

**Comment by spikeydragoon** [comment]
@DTSpawn Not sure shouldnt be but then again at launch of genesis ark did mess russian and german up a little.

Glad its working for you though.
