### ISSUE TITLE
LOCAL chat broadcasting to all

### ISSUE THREAD

**Issue by donmuerte** [spikeydragoon/Cross-Ark-Chat#36]
Issue: LOCAL chat broadcasts to all servers and Discord channel.
Details: I attempted to find a config setting for this or some way of commenting it out in code, but I was unsuccessful. Can this be changed easily?

**Comment by spikeydragoon** [comment]
@donmuerte sadly there is no way to tell difference in local chat vs global via rcon. From what i seen its kinda random though since some servers dont show local chat so my guess is there is a server setting some where in ark that controls that im just not sure where.

**Comment by donmuerte** [comment]
Thanks for the reply. I will looking into my server configs to see if I can have it not send LOCAL to RCON/logs then.
