### ISSUE TITLE
Tool isnt sending

### ISSUE THREAD

**Issue by Kamiikaze** [spikeydragoon/Cross-Ark-Chat#4]
The tool is just recieving messages from the server but if i try to send a msg from discord to server like "hey" or "/ark hey" it wont work.
`  "DiscordSettings": {
    "DiscordChannelID": "458464026720993280",
    "TribeLogsDiscordChannelID": "458464980904181762",
    "prefix": "d!",
    "DiscordToken": "xxx",
    "ShowAdminCommands": false,
    "ShowChatPrefixInDiscord": true,
    "ShowTribelogsInChat": false,
    "SendTribeLogsToOwnChannel": false,
    "SendServerChatToOwnChannel": false,
    "UsePrefixToSendChat": true,
    "PrefixToSendChat": "/ark"`

**Comment by spikeydragoon** [comment]
Make sure your saying that in the Discord channel that you put for the discordchannelid. Also make sure the bot has the proper permissions on the discord server after its added.

**Comment by Kamiikaze** [comment]
Discord Channel: https://i.imgur.com/kW5S9sr.png
Console: https://i.imgur.com/52hAVOk.png
RCON: https://i.imgur.com/oNVCdRo.png

**Comment by spikeydragoon** [comment]
in discord you don't have to put the /ark that prefix you set is only used from the servers side.

**Comment by spikeydragoon** [comment]
another thing to note you can have the rcon window open since they use the same command it will not work properly.

**Comment by Kamiikaze** [comment]
After closing Rcon window, it worked, thx :+1:

**Comment by spikeydragoon** [comment]
Np :)
