### ISSUE TITLE
Issue getting it to work on the servers

### ISSUE THREAD

**Issue by onnarashii** [spikeydragoon/Cross-Ark-Chat#40]
I have posted the code below and not sure what I am missing here to get it to work. Any advice would be great. Thanks!

 },

  "Servers": [
    {
      "Valguero": "Chat1",
      "IP": "104.194.11.241",
      "RconPort": 32330,
      "QueryPort": 27015,
      "Password": "",
      "SettingToUse": 1,
      "Active": true
    },
    {
      "Ragnarok": "Chat2",
      "IP": "104.194.11.241",
      "RconPort": 32340,
      "QueryPort": 27025,
      "Password": "",
      "SettingToUse": 1,
      "Active": true
    },
    {
      "TheIsland": "Chat3",
      "IP": "104.194.11.241",
      "RconPort":32332 ,
      "QueryPort": 27017,
      "Password": "",
      "SettingToUse": 1,
      "Active": true
    },
    {
      "Abberation": "Chat4",
      "IP": "104.194.11.241",
      "RconPort": 32336,
      "QueryPort": 27021,
      "Password": "",
      "SettingToUse": 1,
      "Active": true
    },
    {
      "Extinction": "Chat5",
      "IP": "104.194.11.241",
      "RconPort": 32334,
      "QueryPort": 27019,
      "Password": "",
      "SettingToUse": 1,
      "Active": true
    },
    {
      "ScorchedEarth": "Chat6",
      "IP": "104.194.11.241",
      "RconPort": 32342,
      "QueryPort": 27027,
      "Password": "",
      "SettingToUse": 1,
      "Active": true
    },
    {
      "Genesis": "Chat7",
      "IP": "104.194.11.241",
      "RconPort": 32338,
      "QueryPort": 27023,
      "Password": "",
      "SettingToUse": 1,
      "Active": true
    },
    {
      "CrystalIsles": "Chat8",
      "IP": "104.194.11.241",
      "RconPort": 32344,
      "QueryPort": 27029,
      "Password": "",
      "SettingToUse": 1,
      "Active": true
    }
  ],

  "ServerSettings": [
    {
      "SettingNumber": 1,
      "ServerTag": "",
      "ServerPlayerTag": ":",
      "PlayerChatTag": ":",
      "ChatTag": "",
      "HideNameTag": false,
      "DiscordChannelId": 0
    }
  ],

  "PrefixGroups": [
    {
      "ChatPrefix": "/prefix",
      "ServerList": [
        "chat1",
        "chat2",
	"chat3",
	"chat4",
	"chat5",
	"chat6",
	"chat7",
	"chat8"
      ]
    }

**Comment by spikeydragoon** [comment]
@onnarashii what you posted looks fine but would need to see whole config and need to know whats wrong to help. I edit you message since wasnt sure that was real password if it was i highly suggest changing it.
