### ISSUE TITLE
addd configuration for the senddchat command

### ISSUE THREAD

**Issue by uacaman** [spikeydragoon/Cross-Ark-Chat#41]
Sendchat has a bad font for chat, however the Extend RCON(https://arkserverapi.com/resources/extended-rcon.5/)  has a ClientChat command with a better font and also allows for ArkML.

Having a option to change the SendChat for ClientChat would make me sooo happy.

**Comment by spikeydragoon** [comment]
@uacaman I will be adding that as an option no eta at this time.
Added to the to do list closing.
https://github.com/spikeydragoon/Cross-Ark-Chat/projects/1

**Comment by uacaman** [comment]
Is you need testing, just let me know. Thanks man/woman or draggon!
