### ISSUE TITLE
Bot token incorrect error?

### ISSUE THREAD

**Issue by MolochBaal** [spikeydragoon/Cross-Ark-Chat#42]
I'm setting up CrossArkChat in my server, and as far as I know I've filled in all the required fields in the _configuration.json, but when I launch the program I get this error:
`08:17:42 [Warning] Discord: System.ArgumentException: A Bot token must be at least 58 characters in length. Ensure that the Bot Token provided is not an OAuth client secret. (Parameter 'token') at Discord.TokenUtils.ValidateToken(TokenType tokenType, String token) at Discord.Rest.BaseDiscordClient.LoginInternalAsync(TokenType tokenType, String token, Boolean validateToken)`
`08:17:42 Please close CrossArkChat and check to make sure your DiscordBotToken is correct in the '_configuration.json' file found in the CrossArkChats root directory in the Config folder.`

I don't understand why the bot token should be 58 characters long, mine is 32 chars long.

**Comment by spikeydragoon** [comment]
@MolochBaal sounds like you might be using the client token and not the bot token. Make sure to click on the bot tab and click copy bot token.

**Comment by MolochBaal** [comment]
Oh! You're completely right! Thank you! :D

**Comment by spikeydragoon** [comment]
anytime
