### ISSUE TITLE
Getting started for Linux update to math folder names

### ISSUE THREAD

**Issue by phorce1** [spikeydragoon/Cross-Ark-Chat#43]
<h1 class="western">Prerequisites</h1>
<p>For linux you will need to install libunwind8 for cross ark chat
to work</p>
<p>For Ubuntu/Debian</p>
<pre class="western"><code class="western">sudo apt-get update</code>
<code class="western">sudo apt-get upgrade</code>
<code class="western">sudo apt-get install libunwind8</code></pre><p>
For RedHat/CentOS</p>
<pre class="western"><code class="western">sudo yum update</code>
<code class="western">sudo yum install libunwind libicu nano</code></pre><p>
If you get any System.Net.Http.CurlHandler errors you might need to
install libcurl3 using the methods above just replace libunwind8 with
libcurl3</p>
<p>You must have rcon enabled in the ark server <code class="western">gameusersettings.ini</code>
file. If using ASM you can just check enable rcon in the
administrator section.</p>
<p>For tribe logs to work you must enable Server rcon output tribe
logs in the server launcher settings by adding this tag.
<code class="western">-ServerRCONOutputTribeLogs</code> In ASM you
can just check the Server RCON OUTPUT tribe logs option in the
Administrator section.</p>
<h2 class="western"><a name="user-content-installation-using-systemd-ubuntu-ect"></a>
Installation using Systemd (Ubuntu ect)</h2>
<ol>
	<li/>
<p style="margin-bottom: 0in">Download CrossArkChat for linux
	and transfer it to your linux server via file transfer or however
	you prefer to move your files to and from your linux server. 
	</p>
	<li/>
<p>Set CrossArkChat directory to your home directory and then
	change permissions to the executable file. 
	</p>
</ol>
<pre class="western" style="margin-bottom: 0.2in"><code class="western">chmod u+x /home/&lt;your-username&gt;/CrossArkChat</code><code class="western">Linux</code><code class="western">/CrossArkChat</code></pre>
<ol start="3">
	<li/>
<p>Create a new systemd service for CrossArkChat 
	</p>
</ol>
<pre class="western" style="margin-bottom: 0.2in"><code class="western">sudo nano /lib/systemd/system/CrossArkChat.service </code></pre>
<ol start="4">
	<li/>
<p>Paste the following content and replace User and Group with
	your own username 
	</p>
</ol>
<pre class="western"><code class="western">[Unit]</code>
<code class="western">Description=ARK Cross Chat Service</code>
<code class="western">[Service]</code>
<code class="western">Type=simple</code>
<code class="western">Restart=on-failure</code>
<code class="western">RestartSec=5</code>
<code class="western">StartLimitInterval=60s</code>
<code class="western">StartLimitBurst=3</code>
<code class="western">User=&lt;your-username&gt;</code>
<code class="western">Group=&lt;your-username&gt;</code>
<code class="western">ExecStart=/home/&lt;your-username&gt;/CrossArkChat</code><code class="western">Linux</code><code class="western">/CrossArkChat</code>
<code class="western">ExecReload=/bin/kill -s HUP $MAINPID </code>
<code class="western">ExecStop=/bin/kill -s </code><code class="western">TERM</code><code class="western"> $MAINPID </code>
<code class="western">[Install]</code>
<code class="western">WantedBy=multi-user.target</code></pre>
<ol start="5">
	<li/>
<p style="margin-bottom: 0in">Press Ctrl + x,y (to save),
	Enter (to save with the same name) 
	</p>
	<li/>
<p>Enable the new CrossArkChat service 
	</p>
</ol>
<pre class="western" style="margin-bottom: 0.2in"><code class="western">sudo systemctl enable CrossArkChat.service </code></pre>
<ol start="7">
	<li/>
<p>Reload the Systemd Daemon (Do this every time you modify a
	server file) 
	</p>
</ol>
<pre class="western" style="margin-bottom: 0.2in"><code class="western"><font size="2" style="font-size: 10pt">sudo systemctl daemon-reload</font></code></pre>
<ol start="8">
	<li/>
<p><code class="western"><font size="2" style="font-size: 10pt">**Note
	before starting make sure you edit the
	/home/&lt;your-username&gt;/CrossArkChatLinux/Config/_configuration.json
	file and set up discord if you&rsquo;re linking it to the bot. ** </font></code>
	</p>
	<li/>
<p><code class="western"><font size="2" style="font-size: 10pt">Start
	the CrossArkChat service. You can use start, stop, restart or
	status. You don't have to run it manually again since it's enabled
	to start on boot. <br/>
<br/>
sudo systemctl start
	CrossArkChat.service</font></code><code class="western"> </code>
	</p>
</ol>
<h3 class="western"><a name="user-content-alternative-ways-to-get-crossarkchat-to-run-on-boot-on-different-linux-distros"></a>
Alternative ways to get CrossArkChat to run on boot on different
linux distros</h3>
<p><strong>CrossArkChat using /etc/rc.local (Debian etc) or
/etc/rc.d/boot.local (RedHat etc)</strong></p>
<ol>
	<li/>
<p>Open the /etc/rc.local or /etc/rc.d/boot.local 
	</p>
</ol>
<pre class="western" style="margin-bottom: 0.2in"><code class="western">sudo nano /etc/rc.local</code></pre>
<ol start="2">
	<li/>
<p>Paste the following line at the end of the file and replace
	with your own username. 
	</p>
</ol>
<pre class="western" style="margin-bottom: 0.2in"><code class="western">/home/&lt;your-username&gt;/CrossArkChat</code><code class="western">Linux</code><code class="western">/CrossArkChat</code></pre>
<ol start="3">
	<li/>
<p style="margin-bottom: 0in">Press Ctrl + x, y (to save),
	Enter (to save with the same name). 
	</p>
	<li/>
<p>Run CrossArkChat **Note before starting make sure you edit
	the
	<br/>
<code class="western"><font size="2" style="font-size: 10pt">/home/&lt;your-username&gt;/CrossArkChatLinux/Config/_configuration.json</font></code>
	file and set up discord if you&rsquo;re linking it to the bot. **</p>
</ol>
<pre class="western" style="margin-bottom: 0.2in"><code class="western">cd ~/CrossArkChat</code><code class="western">Linux</code><code class="western"> ./CrossArkChat &amp;</code></pre><p>
<strong>CrossArkChat using crontab for everyone else</strong></p>
<ol>
	<li/>
<p>Open crontab 
	</p>
</ol>
<pre class="western" style="margin-bottom: 0.2in"><code class="western">crontab -e </code></pre>
<ol start="2">
	<li/>
<p>Paste the following line at the end of the file and replace
	with your own username. 
	</p>
</ol>
<pre class="western" style="margin-bottom: 0.2in"><code class="western">@reboot /home/&lt;your-username&gt;/CrossArkChat</code><code class="western">Linux</code><code class="western">/CrossArkChat</code></pre>
<ol start="3">
	<li/>
<p style="margin-bottom: 0in">Press Ctrl + x, y (to save),
	Enter (to save with the same name) 
	</p>
	<li/>
<p>Run CrossArkChat. 
	</p>
</ol>
<pre class="western"><code class="western">**Note: Before starting make sure you edit the <br/>
</code><code class="western"><font size="2" style="font-size: 10pt">/home/&lt;your-username&gt;/CrossArkChatLinux/Config/_configuration.json</font></code><code class="western"> file.**</code>
<code class="western">Set up the discord bot account if you are using the bot with discord.</code>
<code class="western">cd ~/CrossArkChat</code><code class="western">Linux</code><code class="western"> ./CrossArkChat &amp;</code></pre><p style="margin-bottom: 0in; line-height: 100%">
<br/>

</p>
</body>
</html>

**Comment by spikeydragoon** [comment]
@phorce1 thank you page has been updated.
