### ISSUE TITLE
double messages when adding more then 1 server

### ISSUE THREAD

**Issue by Mickroz** [spikeydragoon/Cross-Ark-Chat#44]
Hi,

Im getting double messages when adding a second server to the config.
they both use the same settings number.

**Comment by Mickroz** [comment]
found it, setting this to false worked:
SendServerChatToOwnChannel
SendJoinLeaveNotificationsToServerOwnChannel

**Comment by spikeydragoon** [comment]
@Mickroz yep nice find. Those should only be enabled if you have them using different discord channels.

**Comment by Mickroz** [comment]
Yes, we had multiple servers and channels before, but stopped  playing so we turned the bot off.
No we are playing again, but started with 1 server, and when adding a new server, double messages came up in the chat.
Couldn't find anything with double, but google found this issue which had  a more detailed explanation:
https://github.com/spikeydragoon/Cross-Ark-Chat/issues/15

So for future reference :D
