### ISSUE TITLE
Admin commands on cross chat

### ISSUE THREAD

**Issue by PauloBettin** [spikeydragoon/Cross-Ark-Chat#45]
Hi,

Firsth thanks for your amazing work.

I have used your cross chat after my old api stoped working a month ago.

Your cross chat works greate, and the integration with discord is so good and amazing.

The yellow letters get in the way a lot, but I get the explanation you left on github. 

Is there a something I can´t take from the chat: the admin logs, even doing these settings in the conf file. You could check this out? actually just missing this for your tool to be 100%.

Sorry for my bad english.

Sincerely Paulo

**Comment by spikeydragoon** [comment]
@PauloBettin the admin commands only show in chat if you have server set to something beside English. To fix just check your server logs and see what it calls the admincmd tag. If you paste what it says here or add screen shot i can tell you what to change it to.
"AdminCMDTag": "adminCMD:" is what you are looking to replace to hide admin commands from chat. Each language ark changes what it calls that adminCMD tag.

**Comment by PauloBettin** [comment]
Thanks for the response.

Follows an image with the reported command on discord chat.

Sincerely Paulo.

Em ter., 7 de jul. de 2020 às 14:17, spikeydragoon <notifications@github.com>
escreveu:

**Comment by spikeydragoon** [comment]
@PauloBettin not sure if something happened but I do not see any attached images.

**Comment by PauloBettin** [comment]
Follow the picture, attached to email.

"nome.jpg"


Em ter., 7 de jul. de 2020 às 23:25, spikeydragoon <notifications@github.com>
escreveu:

**Comment by spikeydragoon** [comment]
@PauloBettin I checked both here and the email github generates and there is no image. It is possible github doesn't add attachments from the email reply.
So please either attach it directly using githubs site or join the CrossArkChat [discord](https://discord.gg/HAk4BmN) and send it there.

**Comment by spikeydragoon** [comment]
@PauloBettin per discord conversation for your language 
change
"AdminCMDTag": "AdminCmd:",
to
"AdminCMDTag": "Comando de Admin:",

which you did and said it works so should be good now.
