### ISSUE TITLE
CrossArkChat

### ISSUE THREAD

**Issue by xTryoZ** [spikeydragoon/Cross-Ark-Chat#46]
Hello I would like to know if we can modify the writing of the chat because I find that it is very big the writing between the discord chat via server and from server to server its would be cool if we can put the same writing as the chat original global

**Comment by spikeydragoon** [comment]
@xTryoZ sadly that is just how arks rcon is coded you can not change the size/font/color using just rcon only way to change it is via a mod or ark api plugin.

**Comment by xTryoZ** [comment]
Ok, so impossible because I'm in EPIC steam crossplay

**Comment by phorce1** [comment]
If your server is running on Windows then a plugin should work. It is a server-side solution that does not require the client to download anything. A plugin is not a mod.

**Comment by spikeydragoon** [comment]
No replies for almost a week closing if you have any more issues/questions just open a new ticket or join us in discord server.
