### ISSUE TITLE
Unable to get it working :(

### ISSUE THREAD

**Issue by jraGitHub** [spikeydragoon/Cross-Ark-Chat#47]
I'm not sure what I am doing wrong. But I am unable to get this to work correctly.  I'd be happy to donate if I could use this correctly. Do you offer any setup help?

Thanks in advance.

**Comment by spikeydragoon** [comment]
@jraGitHub I can help you just need to post your config for the bot just make sure to remove the bot token and passwords. Also you can join our discord server for faster replys.

**Comment by spikeydragoon** [comment]
this was fixed over discord.
