### ISSUE TITLE
Chat doesn't scroll down to show latest messages

### ISSUE THREAD

**Issue by TeH-BaK** [spikeydragoon/Cross-Ark-Chat#48]
As this is an Ark issue i'm not certain if you will be able to do a fix for this or not, but when you get multiple multi lined messages from cross server chat - same as if you were to get large amounts of admin logging messages - the chat bugs out and doesn't scroll to the bottom. This isn't too bad for the ark players who know how to scroll the chat with page up and page down, but for new players this is an impassable barrier to read the chat or get the message on how to fix it.

**Comment by spikeydragoon** [comment]
Correct sadly there is nothing i can do rcon wise to fix that only plugin/mod could do something to "refresh" the chat to fix it otherwise fix is to just relog sadly.

**Comment by TeH-BaK** [comment]
If i knew of a mod developer who would be willing to do a mod fix for this, i'd be happy to try finance them and get a client side fix free for all to use.

I guess the solution would either be to force the chat to scroll down, add a clear chat option (intervention required isn't ideal though) or lower the client sides chat log history significantly. (the last not being such an issue with the chat logged in discord)

**Comment by TeH-BaK** [comment]
FYI, I have also sent this as a bug report to wildcard. but i doubt we can expect a fix anytime soon, if at all ;)

**Comment by spikeydragoon** [comment]
Closing since needs mod/plugin/or wildcard to fix.

**Comment by TeH-BaK** [comment]
I think there is a way for this to be fixed by the bot, I've noticed that the chat doesn't bug out when people are just chit chatting, lines no more than two long. but as soon as someone starts writing lots of large bodys of text, it glitches.

It therefore would be possible for the bot to edit these large bodys of text into multiple messages no more than two lines long at a time and avoid the issue.

I haven't been able  to calculate the exact threshold at which it does this, and thats probrably because its not monospaced text, but if you assumed all messages were written in the largest letters e.g. `m` then you could decide a limit to the chars and make more than that overflow to another message.

I would love to know your thoughts on this.
