### ISSUE TITLE
Error msg from discord writing

### ISSUE THREAD

**Issue by Lunnis** [spikeydragoon/Cross-Ark-Chat#52]
hi i use this and it working fine for me to write fron discord but not for anoter admin.
we are both admins on the discord and only admins should be able to write from discord. 
i get this. when the other admin write but not when i write.

[Error] Gateway: System.NullReferenceException: Object reference not set to an instance of an object.
   at Discord.WebSocket.SocketGuild.AddOrUpdateUser(GuildMember model)
   at Discord.WebSocket.DiscordSocketClient.ProcessMessageAsync(GatewayOpCode opCode, Nullable`1 seq, String type, Object payload)

Thanks 
Lunnis

**Comment by spikeydragoon** [comment]
Sorry for delay been away due to moving into new house if your still having issues just reply here or ask away in our discord server.

yeah that was an issue with the discord lib however that should be fixed in newest bot version so give that a try and see if it goes away.
