### ISSUE TITLE
Rest Rate Limit Triggered

### ISSUE THREAD

**Issue by jasontwoody** [spikeydragoon/Cross-Ark-Chat#54]
I'm unable to figure out how to fix this one. I've noticed the discord chat channel has lapses. When I checked the console this was my readout 
06:22:21 [Warning] Rest: Rate limit triggered: channels/727258377113042956

Current Config settings:
"ListPlayerCheckTimeInMs": 10000,
"GetChatTimeInMs": 30000,
"PlayerCountCheckTimeInMs": 30000,
"VersionCheckTimeInMs": 3600000,
"RconSendTimeoutInMs": 6000,
"RconReceiveTimeoutInMs": 45000,
"RconConnectionRetrys": 10

the RCON is running just fine but the chat is only working for about 3-5 minutes and then stops responding until it is restarted.

**Comment by spikeydragoon** [comment]
The default rcon settings is fine so no need to pad them like that unless you meant to.

The rate limit is usually caused when you have tons of things going to the same channel so only way to help is if you upload your config file however if you do make sure to remove the password and bot token first.

**Comment by jasontwoody** [comment]
{
    "ApplicationSettings": {
        "VersionCheckUrl": "https://raw.githubusercontent.com/spikeydragoon/Cross-Ark-Chat/master/version.txt",
        "PatchNotesCheckUrl": "https://raw.githubusercontent.com/spikeydragoon/Cross-Ark-Chat/master/CrossArkChatPatchNotes.txt",
        "LogErrors": true,
        "LogChat": true,
        "LogAdminCommands": true,
        "LogTribeLogs": true,
        "UseDiscord": true,
        "DiscordLogSeverity": "info"
    },

    "Servers": [{
            "NameTag": "Ragnarok",
            "IP": "199.127.63.252",
            "RconPort": 28038,
            "QueryPort": 28035,
            "Password": "REMOVED",
            "SettingToUse": 1,
            "Active": true
        },
        {
            "NameTag": "CrystalIsles",
            "IP": "199.127.63.252",
            "RconPort": 28048,
            "QueryPort": 28045,
            "Password": "REMOVED",
            "SettingToUse": 1,
            "Active": true
        },
        {
            "NameTag": "TheCenter",
            "IP": "199.127.63.252",
            "RconPort": 28068,
            "QueryPort": 28065,
            "Password": "REMOVED",
            "SettingToUse": 1,
            "Active": true
        },
        {
            "NameTag": "Extinction",
            "IP": "199.127.63.252",
            "RconPort": 28088,
            "QueryPort": 28085,
            "Password": "REMOVED",
            "SettingToUse": 1,
            "Active": true
        },
        {
            "NameTag": "Abberation",
            "IP": "199.127.63.252",
            "RconPort": 28098,
            "QueryPort": 28095,
            "Password": "REMOVED",
            "SettingToUse": 1,
            "Active": true
        },
        {
            "NameTag": "EC",
            "IP": "199.127.63.252",
            "RconPort": 28128,
            "QueryPort": 28125,
            "Password": "REMOVED",
            "SettingToUse": 1,
            "Active": true
        },
        {
            "NameTag": "Valguero",
            "IP": "199.127.63.252",
            "RconPort": 28018,
            "QueryPort": 28015,
            "Password": "REMOVED",
            "SettingToUse": 1,
            "Active": true
        },
        {
            "NameTag": "TheIsland",
            "IP": "199.127.63.252",
            "RconPort": 28028,
            "QueryPort": 28025,
            "Password": "REMOVED",
            "SettingToUse": 1,
            "Active": true
        },
        {
            "NameTag": "Genesis",
            "IP": "199.127.63.252",
            "RconPort": 28138,
            "QueryPort": 28135,
            "Password": "REMOVED",
            "SettingToUse": 1,
            "Active": true
        },
        {
            "NameTag": "BionicPrimalFear",
            "IP": "199.127.63.252",
            "RconPort": 28148,
            "QueryPort": 28145,
            "Password": "REMOVED",
            "SettingToUse": 1,
            "Active": true
        }
    ],

    "ServerSettings": [{
            "SettingNumber": 1,
            "ServerTag": "",
            "ServerPlayerTag": ":",
            "PlayerChatTag": ":",
            "ChatTag": "",
            "HideNameTag": false,
            "DiscordChannelId": 0
        }
    ],

    "PrefixGroups": [{
            "ChatPrefix": "/prefix",
            "ServerList": [
                "CrystalIsles",
                "Ragnarok",
                "TheCenter",
                "Extinction",
                "Abberation",
                "ExtinctionCore",
                "TheIsland",
                "Genesis",
                "BionicPrimalFear"
            ]
        },
        {
            "ChatPrefix": "/prefix2",
            "ServerList": [
                "chat1",
                "chat2",
                "chat3",
                "chat4",
                "chat5",
                "chat6",
                "chat7",
                "chat8",
                "chat9"
            ]
        }
    ],

    "Tribes": [{
            "TribeId": "1541237457",
            "SettingToUse": 1,
            "Active": true
        },
        {
            "TribeId": "1052580629",
            "SettingToUse": 2,
            "Active": true
        },
        {
            "TribeId": "1877986862",
            "SettingToUse": 2,
            "Active": true
        },
        {
            "TribeId": "1773211218",
            "SettingToUse": 2,
            "Active": true
        },
        {
            "TribeId": "1447631727",
            "SettingToUse": 2,
            "Active": true
        },
        {
            "TribeId": "1623127112",
            "SettingToUse": 2,
            "Active": true
        },
        {
            "TribeId": "1463907076",
            "SettingToUse": 2,
            "Active": true
        },
        {
            "TribeId": "1156051953",
            "SettingToUse": 2,
            "Active": true
        },
        {
            "TribeId": "1466382767",
            "SettingToUse": 3,
            "Active": true
        },
        {
            "TribeId": "1273183028",
            "SettingToUse": 3,
            "Active": true
        },
        {
            "TribeId": "1658498585",
            "SettingToUse": 3,
            "Active": true
        },
        {
            "TribeId": "1259506571",
            "SettingToUse": 3,
            "Active": true
        },
        {
            "TribeId": "1132337276",
            "SettingToUse": 3,
            "Active": true
        },
        {
            "TribeId": "1487597523",
            "SettingToUse": 4,
            "Active": true
        },
        {
            "TribeId": "1337098007",
            "SettingToUse": 5,
            "Active": true
        },
        {
            "TribeId": "1483968093",
            "SettingToUse": 6,
            "Active": true
        },
        {
            "TribeId": "1357600434",
            "SettingToUse": 7,
            "Active": true
        },
        {
            "TribeId": "1835378123",
            "SettingToUse": 8,
            "Active": true
        },
        {
            "TribeId": "1855209704",
            "SettingToUse": 9,
            "Active": true
        },
        {
            "TribeId": "1376001606",
            "SettingToUse": 10,
            "Active": true
        },
        {
            "TribeId": "1168733299",
            "SettingToUse": 11,
            "Active": true
        },
        {
            "TribeId": "1567453246",
            "SettingToUse": 12,
            "Active": true
        },
        {
            "TribeId": "1142888987",
            "SettingToUse": 12,
            "Active": true
        },
        {
            "TribeId": "1536279780",
            "SettingToUse": 13,
            "Active": true
        },
        {
            "TribeId": "1247828202",
            "SettingToUse": 13,
            "Active": true
        },
        {
            "TribeId": "1320605027",
            "SettingToUse": 13,
            "Active": true
        },
        {
            "TribeId": "1859088038",
            "SettingToUse": 14,
            "Active": true
        },
        {
            "TribeId": "1623544144",
            "SettingToUse": 14,
            "Active": true
        }
    ],

    "TribeSettings": [{
            "SettingNumber": 1,
            "ShowFullTribeLog": false,
            "ShowTribeName": true,
            "ShowServerName": true,
            "ShowTribeId": true,
            "EmbedTribeLog": true,
            "DiscordChannelId": 727354214694518824
        },
        {
            "SettingNumber": 2,
            "ShowFullTribeLog": false,
            "ShowTribeName": true,
            "ShowServerName": true,
            "ShowTribeId": true,
            "EmbedTribeLog": true,
            "DiscordChannelId": 741750517352628276
        },
        {
            "SettingNumber": 3,
            "ShowFullTribeLog": false,
            "ShowTribeName": true,
            "ShowServerName": true,
            "ShowTribeId": true,
            "EmbedTribeLog": true,
            "DiscordChannelId": 741748753203069029
        },
        {
            "SettingNumber": 4,
            "ShowFullTribeLog": false,
            "ShowTribeName": true,
            "ShowServerName": true,
            "ShowTribeId": true,
            "EmbedTribeLog": true,
            "DiscordChannelId": 741790104313659473
        },
        {
            "SettingNumber": 5,
            "ShowFullTribeLog": false,
            "ShowTribeName": true,
            "ShowServerName": true,
            "ShowTribeId": true,
            "EmbedTribeLog": true,
            "DiscordChannelId": 741877769646112779
        },
        {
            "SettingNumber": 6,
            "ShowFullTribeLog": false,
            "ShowTribeName": true,
            "ShowServerName": true,
            "ShowTribeId": true,
            "EmbedTribeLog": true,
            "DiscordChannelId": 777691722582589440
        },
        {
            "SettingNumber": 7,
            "ShowFullTribeLog": false,
            "ShowTribeName": true,
            "ShowServerName": true,
            "ShowTribeId": true,
            "EmbedTribeLog": true,
            "DiscordChannelId": 779161401767100457
        },
        {
            "SettingNumber": 8,
            "ShowFullTribeLog": false,
            "ShowTribeName": true,
            "ShowServerName": true,
            "ShowTribeId": true,
            "EmbedTribeLog": true,
            "DiscordChannelId": 779356061022683176
        },
        {
            "SettingNumber": 9,
            "ShowFullTribeLog": false,
            "ShowTribeName": true,
            "ShowServerName": true,
            "ShowTribeId": true,
            "EmbedTribeLog": true,
            "DiscordChannelId": 781385882623148032
        },
        {
            "SettingNumber": 10,
            "ShowFullTribeLog": false,
            "ShowTribeName": true,
            "ShowServerName": true,
            "ShowTribeId": true,
            "EmbedTribeLog": true,
            "DiscordChannelId": 782609238643703839
        },
        {
            "SettingNumber": 11,
            "ShowFullTribeLog": false,
            "ShowTribeName": true,
            "ShowServerName": true,
            "ShowTribeId": true,
            "EmbedTribeLog": true,
            "DiscordChannelId": 783736279451435119
        },
        {
            "SettingNumber": 12,
            "ShowFullTribeLog": false,
            "ShowTribeName": true,
            "ShowServerName": true,
            "ShowTribeId": true,
            "EmbedTribeLog": true,
            "DiscordChannelId": 784071134332059649
        },
        {
            "SettingNumber": 13,
            "ShowFullTribeLog": false,
            "ShowTribeName": true,
            "ShowServerName": true,
            "ShowTribeId": true,
            "EmbedTribeLog": true,
            "DiscordChannelId": 785554357730672660
        },
        {
            "SettingNumber": 14,
            "ShowFullTribeLog": false,
            "ShowTribeName": true,
            "ShowServerName": true,
            "ShowTribeId": true,
            "EmbedTribeLog": true,
            "DiscordChannelId": 785600620417646603
        }
    ],

    "GameCommands": [{
            "Command": "!discord",
            "CommandReply": "https://discord.gg/34QBXww",
            "Active": true
        },
        {
            "Command": "rules",
            "CommandReply": "These are the rules.",
            "Active": false
        },
        {
            "Command": "/ping",
            "CommandReply": "Pong!",
            "Active": true
        }
    ],

    "CustomTagList": [
        "ACM[CMD]",
        "SERVER: ACM[CMD]"
    ],

    "RconSettings": {
        "NoResponceTag": "Server received, But no response!!",
        "NoPlayerTag": "No Players Connected",
        "ServerRepeatTag": "SERVER:",
        "AdminCMDTag": "AdminCmd:",
        "TribeLogTag": "Tribe",
        "GetChatCmd": "getchat",
        "ListPlayersCmd": "ListPlayers",
        "ListPlayerCheckTimeInMs": 10000,
        "GetChatTimeInMs": 30000,
        "PlayerCountCheckTimeInMs": 30000,
        "VersionCheckTimeInMs": 3600000,
        "RconSendTimeoutInMs": 6000,
        "RconReceiveTimeoutInMs": 45000,
        "RconConnectionRetrys": 10
    },

    "EmbeddedTribeLogColorSettings": [{
            "LogType": "killed",
            "LogColor": "ff2121",
            "RoleToPing": "none"
        },
        {
            "LogType": "demolished",
            "LogColor": "ff2121",
            "RoleToPing": "none"
        },
        {
            "LogType": "claimed",
            "LogColor": "03f413",
            "RoleToPing": "none"
        },
        {
            "LogType": "unclaimed",
            "LogColor": "ff2121",
            "RoleToPing": "none"
        },
        {
            "LogType": "tamed",
            "LogColor": "03f413",
            "RoleToPing": "none"
        },
        {
            "LogType": "destroyed",
            "LogColor": "ff7400",
            "RoleToPing": "none"
        },
        {
            "LogType": "froze",
            "LogColor": "d8ddd8",
            "RoleToPing": "none"
        },
        {
            "LogType": "downloaded",
            "LogColor": "03f413",
            "RoleToPing": "none"
        },
        {
            "LogType": "uploaded",
            "LogColor": "ff2121",
            "RoleToPing": "none"
        },
        {
            "LogType": "starved",
            "LogColor": "ff2121",
            "RoleToPing": "none"
        }
    ],

    "ChatSettings": {
        "UseCustomTags": false,
        "SendChatToServers": true,
        "ShowAdminCommands": false,
        "UseGameCommands": false,
        "UsePrefixToSendChat": false,
        "UseWordReplacementList": false,
        "AllServersChatPrefix": "/all"
    },

    "DiscordSettings": {
        "DiscordBotSettings": {
            "CommandPrefix": "d!",
            "DiscordBotToken": "REMOVED",
            "IgnoreOtherBots": true,
            "ShowDiscordNickName": true
        },

        "ServerChatSettings": {
            "ChatDiscordChannelID": 727258377113042956,
            "SendServerChatToOwnChannel": false
        },

        "DiscordChatSettings": {
            "DiscordChatPrefix": "Discord",
            "SendChatToDiscord": true,
            "UsePrefixToSendToDiscord": false,
            "PrefixToSendToDiscord": "/discord"
        },

        "NotificationSettings": {
            "VersionDiscordChannelId": 727350734814707802,
            "PatchNotesDiscordChannelId": 727350086589218866,
            "JoinLeaveNotificationsDiscordChannelID": 727349645369409536,
            "UseVersionChecker": true,
            "UsePatchNotesChecker": true,
            "UseJoinLeaveNotifications": true,
            "UsePlayerCountChannelUpdater": true,
            "SendJoinLeaveNotificationsToServerOwnChannel": true
        },

        "AdminCommandSettings": {
            "AdminCommandsDiscordChannelID": 727290696930951199,
            "SendAdminCommandsToOwnChannel": true
        },

        "TribeLogSettings": {
            "TribeLogsDiscordChannelID": 741747419930427464,
            "ShowTribelogs": true,
            "ShowFullTribeLog": true,
            "ShowTribeId": true,
            "ShowTribeName": true,
            "ShowServerName": true,
            "EmbedTribeLog": true,
            "SendTribeLogsToOwnChannel": true
        },

        "SupportSettings": {
            "SupportDiscordChannelID": 727351096107991060,
            "UseSupportPrefix": true,
            "PingRoleName": true,
            "ReplyToSupportPing": true,
            "SupportPrefix": "/support",
            "SupportRoleToPing": "Support",
            "SupportPingReply": "Your support ticket has been sent."
        }
    }
}

**Comment by jasontwoody** [comment]
thank you I'll swap the rcon settings back to default

**Comment by jasontwoody** [comment]
still receiving that error with default settings. Is there anything else i can configure? What was nice about the bot (part of why we moved to serverblend) was we could have a central chat in discord to communicate to players across the cluster

**Comment by spikeydragoon** [comment]
Two changes should fix that.
1: change SendJoinLeaveNotificationsToServerOwnChannel to false
2: the main cause is the player count update its known to cause ratelimites and is buggy so set UsePlayerCountChannelUpdater to false

After doing those you should not get rate limits anymore.
