### ISSUE TITLE
Cross Chat switch between local and cluster chat

### ISSUE THREAD

**Issue by GyrosWookiedaris** [spikeydragoon/Cross-Ark-Chat#58]
Hello,

not an issue, just a question because I haven't found something in the docs.

Is it possible for a single user to only show the local chatlog and not all messages via rcon? So if someones feels spammed by this feature he only may use the local chat?

**Comment by spikeydragoon** [comment]
@GyrosWookiedaris Sadly there is currently no way to do that over just rcon. Only plugs/mods are able to edit chat like that including text size/color as well.
