### ISSUE TITLE
Ip

### ISSUE THREAD

**Issue by ZaneMgz** [spikeydragoon/Cross-Ark-Chat#60]
Is there any way to make a variable that I can change, to change all the other ip's from line 15 forward?

**Comment by spikeydragoon** [comment]
@ZaneMgz Not sure what you mean.

Currently only way to change ips is to manually do it from the config. Now in new setup im working on this wont be an issue since ill add support for domain names.

**Comment by ZaneMgz** [comment]
> @ZaneMgz Not sure what you mean.
> 
> Currently only way to change ips is to manually do it from the config. Now in new setup im working on this wont be an issue since ill add support for domain names.

Yes, that is what I meant, thanks for answering.
