### ISSUE TITLE
Launching CrossArkChat.exe opens then closes immediately.

### ISSUE THREAD

**Issue by MasterBLaha** [spikeydragoon/Cross-Ark-Chat#64]
Hello I'm running this on a dedicated machine via Windows Server 2019 not sure what's wrong configuration file looks perfect, any ideas? I've tried running this as an administrator still does the same thing.  I managed to grab a screen shot of the program when it boots up before closing.
![CrossArkChat](https://user-images.githubusercontent.com/69664674/176583920-bfb4bbf9-3400-46f3-bc03-a3d385f5f1d5.png)

**Comment by spikeydragoon** [comment]
> 

I would need to see more of the error to be able to tell whats going on but basically something in the config format wise is not right. You can use sites like https://jsonlint.com/ to point you where it needs fixing. You can also post the config (after removing passwords and bot token) and I can take a look to see whats wrong.

**Comment by MasterBLaha** [comment]
Error: Parse error on line 1:
//For all info on co
^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'
JSONLint Partners


//For all info on config visit https://github.com/spikeydragoon/Cross-Ark-Chat and look at the readme file as it goes over all config information.
// DO NOT change anything in the Rcon settings unless you know what you are doing!!!
{
  "ApplicationSettings": {
    "VersionCheckUrl": "https://raw.githubusercontent.com/spikeydragoon/Cross-Ark-Chat/master/version.txt",
    "PatchNotesCheckUrl": "https://raw.githubusercontent.com/spikeydragoon/Cross-Ark-Chat/master/CrossArkChatPatchNotes.txt",
    "LogErrors": true,
    "LogChat": true,
    "LogAdminCommands": false,
    "LogTribeLogs": true,
    "UseDiscord": false,
    "DiscordLogSeverity": "info"
  },

  "Servers": [
    {
      "NameTag": "Aberration",
      "IP": "192.168.1.5",
      "RconPort": 32340,
      "QueryPort": 27025,
      "Password": "******",
      "SettingToUse": 1,
      "Active": true
    },
    {
      "NameTag": "Crystal Isles",
      "IP": "192.168.1.5",
      "RconPort": 32346,
      "QueryPort": 27031,
      "Password": "******",
      "SettingToUse": 1,
      "Active": true
    },
    {
      "NameTag": "Extinction",
      "IP": "192.168.1.5",
      "RconPort": 32342,
      "QueryPort": 27027,
      "Password": "******",
      "SettingToUse": 1,
      "Active": true
    },
    {
      "NameTag": "Genesis",
      "IP": "192.168.1.5",
      "RconPort": 32344,
      "QueryPort": 27029,
      "Password": "******",
      "SettingToUse": 1,
      "Active": true
    },
    {
      "NameTag": "Genesis 2",
      "IP": "192.168.1.5",
      "RconPort": 32350,
      "QueryPort": 27035,
      "Password": "******",
      "SettingToUse": 1,
      "Active": true
    },
    {
      "NameTag": "Lost Island",
      "IP": "192.168.1.5",
      "RconPort": 32348,
      "QueryPort": 27033,
      "Password": "******",
      "SettingToUse": 1,
      "Active": true
    },
    {
      "NameTag": "Ragnarok",
      "IP": "192.168.1.5",
      "RconPort": 32334,
      "QueryPort": 27019,
      "Password": "******",
      "SettingToUse": 1,
      "Active": true
    },
    {
      "NameTag": "Scorched Earth",
      "IP": "192.168.1.5",
      "RconPort": 32338,
      "QueryPort": 27023,
      "Password": "******",
      "SettingToUse": 1,
      "Active": true
    },
    {
      "NameTag": "The Center",
      "IP": "192.168.1.5",
      "RconPort": 32330,
      "QueryPort": 27015,
      "Password": "******",
      "SettingToUse": 1,
      "Active": true
    },
    {
      "NameTag": "The Island",
      "IP": "192.168.1.5",
      "RconPort": 32336,
      "QueryPort": 27021,
      "Password": "******",
      "SettingToUse": 1,
      "Active": true
    },
    {
      "NameTag": "Valguero",
      "IP": "192.168.1.5",
      "RconPort": 32332,
      "QueryPort": 27017,
      "Password": "******",
      "SettingToUse": 1,
      "Active": true
    }
  ],
  
  "ServerSettings": [
    {
      "SettingNumber": 1,
      "ServerTag": "",
      "ServerPlayerTag": ":",
      "PlayerChatTag": ":",
      "ChatTag": "",
      "HideNameTag": false,
      "DiscordChannelId": 0
    },

  "PrefixGroups": [
    {
      "ChatPrefix": "/Abe",
      "ServerList": [
        "Aberration",
      ]
    },
    {
      "ChatPrefix": "/Cry",
      "ServerList": [
        "Crystal Isles",
      ]
    }
    {
      "ChatPrefix": "/Ext",
      "ServerList": [
        "Extinction",
      ]
    }
    {
      "ChatPrefix": "/Gen",
      "ServerList": [
        "Genesis",
      ]
    }
    {
      "ChatPrefix": "/Gen2",
      "ServerList": [
        "Genesis 2",
      ]
    }
    {
      "ChatPrefix": "/Los",
      "ServerList": [
        "Lost Island",
      ]
    }
    {
      "ChatPrefix": "/Rag",
      "ServerList": [
        "Ragnarok",
      ]
    }
    {
      "ChatPrefix": "/Sco",
      "ServerList": [
        "Scorched Earth",
      ]
    }
    {
      "ChatPrefix": "/Cry",
      "ServerList": [
        "Crystal",
      ]
    }
    {
      "ChatPrefix": "/Cen",
      "ServerList": [
        "The Center",
      ]
    }
    {
      "ChatPrefix": "/Val",
      "ServerList": [
        "Valguero",
      ]
    }
  ],

  "Tribes": [
    {
      "TribeId": "00000",
      "SettingToUse": 1,
      "Active": false
    },
    {
      "TribeId": "00000",
      "SettingToUse": 2,
      "Active": false
    }
  ],

  "TribeSettings": [
    {
      "SettingNumber": 1,
      "ShowFullTribeLog": false,
      "ShowTribeName": false,
      "ShowServerName": true,
      "ShowTribeId": false,
      "EmbedTribeLog": true,
      "DiscordChannelId": 0
    },
    {
      "SettingNumber": 2,
      "ShowFullTribeLog": false,
      "ShowTribeName": false,
      "ShowServerName": true,
      "ShowTribeId": false,
      "EmbedTribeLog": true,
      "DiscordChannelId": 0
    }
  ],

  "GameCommands": [
    {
      "Command": "!discord",
      "CommandReply": "https://discord.gg/",
      "Active": false
    },
    {
      "Command": "rules",
      "CommandReply": "These are the rules.",
      "Active": false
    },
    {
      "Command": "/ping",
      "CommandReply": "Pong!",
      "Active": false
    }
  ],

  "CustomTagList": [
    "ACM[CMD]",
    "SERVER: ACM[CMD]"
  ],

  "RconSettings": {
    "NoResponceTag": "Server received, But no response!!",
    "NoPlayerTag": "No Players Connected",
    "ServerRepeatTag": "SERVER:",
    "AdminCMDTag": "AdminCmd:",
    "TribeLogTag": "Tribe",
    "GetChatCmd": "getchat",
    "ListPlayersCmd": "ListPlayers",
    "ListPlayerCheckTimeInMs": 10000,
    "GetChatTimeInMs": 1000,
    "PlayerCountCheckTimeInMs": 30000,
    "VersionCheckTimeInMs": 3600000,
    "RconSendTimeoutInMs": 3000,
    "RconReceiveTimeoutInMs": 10000,
    "RconConnectionRetrys": 1
  },

  "EmbeddedTribeLogColorSettings": [
    {
      "LogType": "killed",
      "LogColor": "ff2121",
      "RoleToPing": "none"
    },
    {
      "LogType": "demolished",
      "LogColor": "ff2121",
      "RoleToPing": "none"
    },
    {
      "LogType": "claimed",
      "LogColor": "03f413",
      "RoleToPing": "none"
    },
    {
      "LogType": "unclaimed",
      "LogColor": "ff2121",
      "RoleToPing": "none"
    },
    {
      "LogType": "tamed",
      "LogColor": "03f413",
      "RoleToPing": "none"
    },
    {
      "LogType": "destroyed",
      "LogColor": "ff7400",
      "RoleToPing": "none"
    },
    {
      "LogType": "froze",
      "LogColor": "d8ddd8",
      "RoleToPing": "none"
    },
    {
      "LogType": "downloaded",
      "LogColor": "03f413",
      "RoleToPing": "none"
    },
    {
      "LogType": "uploaded",
      "LogColor": "ff2121",
      "RoleToPing": "none"
    },
    {
      "LogType": "starved",
      "LogColor": "ff2121",
      "RoleToPing": "none"
    }
  ],

  "ChatSettings": {
    "UseCustomTags": false,
    "SendChatToServers": true,
    "ShowAdminCommands": false,
    "UseGameCommands": false,
    "UsePrefixToSendChat": false,
    "UseWordReplacementList": false,
    "AllServersChatPrefix": "/all"
  },

  "DiscordSettings": {
    "DiscordBotSettings": {
      "CommandPrefix": "d!",
      "DiscordBotToken": "BotToken",
      "IgnoreOtherBots": true,
      "ShowDiscordNickName": true
    },

    "ServerChatSettings": {
      "ChatDiscordChannelID": 0,
      "SendServerChatToOwnChannel": false
    },

    "DiscordChatSettings": {
      "DiscordChatPrefix": "Discord",
      "SendChatToDiscord": true,
      "UsePrefixToSendToDiscord": false,
      "PrefixToSendToDiscord": "/discord"
    },

    "NotificationSettings": {
      "VersionDiscordChannelId": 0,
      "PatchNotesDiscordChannelId": 0,
      "JoinLeaveNotificationsDiscordChannelID": 0,
      "UseVersionChecker": false,
      "UsePatchNotesChecker": false,
      "UseJoinLeaveNotifications": false,
      "UsePlayerCountChannelUpdater": false,
      "SendJoinLeaveNotificationsToServerOwnChannel": false
    },

    "AdminCommandSettings": {
      "AdminCommandsDiscordChannelID": 0,
      "SendAdminCommandsToOwnChannel": false
    },

    "TribeLogSettings": {
      "TribeLogsDiscordChannelID": 0,
      "ShowTribelogs": false,
      "ShowFullTribeLog": false,
      "ShowTribeId": true,
      "ShowTribeName": true,
      "ShowServerName": true,
      "EmbedTribeLog": true,
      "SendTribeLogsToOwnChannel": false
    },

    "SupportSettings": {
      "SupportDiscordChannelID": 0,
      "UseSupportPrefix": false,
      "PingRoleName": false,
      "ReplyToSupportPing": true,
      "SupportPrefix": "/help",
      "SupportRoleToPing": "rolename",
      "SupportPingReply": "Your support ticket has been sent."
    }
  }
}

**Comment by spikeydragoon** [comment]
@MasterBLaha The first thing would be to remove the spaces in the name tags. Example instead of The Island do The_Island or TheIsland or The-Island ect anything but a space will work. Note those are just nicknames so you can all it something other than the map name.

Next thing to fix would be those prefixes. Since you are not using them I would just remove them or fix the formatting. Basically you are missing a lot of , after each prefix however if your not using prefixes you can just remove those.

**Comment by MasterBLaha** [comment]
Copy of the Config File is here:
[https://www.dropbox.com/s/dmngxbn95mdi0mj/_configuration%20-%20Copy.json?dl=0](url)

Error: Parse error on line 1:
//For all info on co
^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'
JSONLint Partners

**Comment by spikeydragoon** [comment]
@MasterBLaha  Example of how to fix format of the prefix group would be.

wrong
```
{
      "ChatPrefix": "/Cen",
      "ServerList": [
        "The Center",
      ]
} <-- notice the missing ,
{
      "ChatPrefix": "/Val",
      "ServerList": [
        "Valguero",
      ]
}
```

Fixed

```
{
      "ChatPrefix": "/Cen",
      "ServerList": [
        "The Center",
      ]
}, <-- all but the last one needs this
{
      "ChatPrefix": "/Val",
      "ServerList": [
        "Valguero",
      ]
}
```

**Comment by MasterBLaha** [comment]
OK I just cleaned it all up ,that's my bad for missing those and I really appreciate you replying back to me so quickly. It's working well now, Thank You!
