### ISSUE TITLE
admin command channel

### ISSUE THREAD

**Issue by Mickroz** [spikeydragoon/Cross-Ark-Chat#67]
Hi, i want to have the admin level commands for the bots only to work in a admin channel, and all other user level commands in the chat channel, how do i set this up if its possible?

**Comment by spikeydragoon** [comment]
@Mickroz Set SendAdminCommandsToOwnChannel to true and leave ShowAdminCommands set to false.
That will make all admin commands only show up in the channel set in AdminCommandsDiscordChannelID.

Also for this to work your server either needs to be set to english or for you to change the AdminCMDTag to whatever ark uses for your language. The bot defaults to use all english tags but under rcon settings section you can change it to match any language.

**Comment by Mickroz** [comment]
Thanks, will see if that works.

**Comment by spikeydragoon** [comment]
Closing due to no update.

If your still having issues please reopen the ticket. 
For faster support you can also join the discord server and ask under the support channel.

**Comment by Mickroz** [comment]
Sorry, totally forgot about it, it works
