### ISSUE TITLE
Discord Message don't show

### ISSUE THREAD

**Issue by mK33y** [spikeydragoon/Cross-Ark-Chat#68]
https://prnt.sc/BUV5FRp7zhmx

If I send a message from discord to ingame chat this happens.

**Comment by spikeydragoon** [comment]
> https://prnt.sc/BUV5FRp7zhmx
> 
> If I send a message from discord to ingame chat this happens.

Discord changed a few requirements for bots now so you do this in the discord developer portal under the bot tab for the bot account you created.
![image](https://user-images.githubusercontent.com/29191122/194978091-da0640cb-4b09-438d-a787-09f362f78849.png)

That will fix the empty message content.

**Comment by mK33y** [comment]
Knew I missed something. Fixed it, but which settings will fix my next problem. https://prnt.sc/J-Q2qLhF0lKI
Tribe Name is not shown. Is there even a setting for this?

**Comment by spikeydragoon** [comment]
Sadly tribe name is not sent over arks rcon system. Only in-game name and steam name. I currently filter steam name out.
