### ISSUE TITLE
Source

### ISSUE THREAD

**Issue by earmbrust** [spikeydragoon/Cross-Ark-Chat#69]
Release the source if this isn't a scam, trojan, or another cheap and pathetic moneygrab for minimal work.

**Comment by spikeydragoon** [comment]
> Release the source if this isn't a scam, trojan, or another cheap and pathetic moneygrab for minimal work.

This program is not open source, I only use github to host the download files so I will not be releasing the source code nor am I required to.

It has been around for 4 years with an active discord community so if it was a scam/trojan people would have reported it by now.
Its has been free to use without any pay walls and free support for the past 4 years so not sure where you got money grab from.

So next time before you make another cheap and pathetic attempt to get someones work for free with minimal effort do some research first or program it yourself.
