### ISSUE TITLE
[Idea] - run a shell command (script)

### ISSUE THREAD

**Issue by ToeiRei** [spikeydragoon/Cross-Ark-Chat#73]
My idea would be - as the d! commands are locked to roles - giving staff the ability to run a restart script for the server to get all mods up to date.

**Comment by spikeydragoon** [comment]
Yes I can look into allowing it to run custom scripts with the new custom commands system I am working on. In terms of updates for the server/mods since its not a server manager you would have to handle that on your side with the scirpts.

**Comment by ToeiRei** [comment]
Updating usually happens automatically on server restarts as ark tries to do that on startup.

Running commands based on discord rules as you do, makes a huge difference as you can let players check who is online while not being allowed to shut down the server.

**Comment by spikeydragoon** [comment]
Closing added to to-do
