### ISSUE TITLE
What is the install procedure for this for people that use hosted ark servers?

### ISSUE THREAD

**Issue by Fullstackopolis** [spikeydragoon/Cross-Ark-Chat#74]
What is the install procedure for this for people that use hosted ark servers?

**Comment by spikeydragoon** [comment]
If its a provider that will host the bot for you like serverblend then you would just follow their instructions on how to install the bot.

If its a provider that does not allow bot hosting then you would have to run it on your own pc or rent a cheap vm some where to run the bot from.

**Comment by Fullstackopolis** [comment]
Thanks Spikey; I found your discord channel and it's a wealth of help. I'll close this issue; Thanks!
