### ISSUE TITLE
Unraid Docker request

### ISSUE THREAD

**Issue by tbgkiller** [spikeydragoon/Cross-Ark-Chat#78]
Hello, I am running a cluster on Unraid and would like to create/use a docker version of this. Is it too late in the game to ask for this?

**Comment by spikeydragoon** [comment]
Currently I have no plans to make an official docker image at this time however using the latest linux version of the bot (v6.3.0 is container/docker friendly) you should be able to create a basic container then install the bot on it then create image of it to reuse.

I am currently running the bot on proxmox container and a few others in the community made their own docker image for it.

If you have any other questions on this you can reopen ticket or ask on the discord server.
