### ISSUE TITLE
chat blank

### ISSUE THREAD

**Issue by adler234639** [spikeydragoon/Cross-Ark-Chat#80]
When I chat from Discord to in game it shows the name but no text. What have I done wrong?

![chat](https://github.com/spikeydragoon/Cross-Ark-Chat/assets/138949374/35f1634c-05ee-474d-b022-342c8f42aaf3)

//For all info on config visit https://github.com/spikeydragoon/Cross-Ark-Chat and look at the readme file as it goes over all config information.
// DO NOT change anything in the Rcon settings unless you know what you are doing!!!
{
  "ApplicationSettings": {
    "VersionCheckUrl": "https://raw.githubusercontent.com/spikeydragoon/Cross-Ark-Chat/master/version.txt",
    "PatchNotesCheckUrl": "https://raw.githubusercontent.com/spikeydragoon/Cross-Ark-Chat/master/CrossArkChatPatchNotes.txt",
    "LogErrors": true,
    "LogChat": true,
    "LogAdminCommands": true,
    "LogTribeLogs": true,
    "UseDiscord": true,
    "DiscordLogSeverity": "info"
  },

  "Servers": [
    {
      "NameTag": "Island",
      "IP": "172.240.137.108",
      "RconPort": 11740,
      "QueryPort": 5740,
      "Password": "password",
      "SettingToUse": 1,
      "Active": true
    },
    {
      "NameTag": "Chat2",
      "IP": "0.0.0.0",
      "RconPort": 0,
      "QueryPort": 0,
      "Password": "Password",
      "SettingToUse": 2,
      "Active": false
    }
  ],

  "ServerSettings": [
    {
      "SettingNumber": 1,
      "ServerTag": ":",
      "ServerPlayerTag": ":",
      "PlayerChatTag": ":",
      "ChatTag": "",
      "HideNameTag": false,
      "DiscordChannelId": 1192284714120261712
    },
    {
      "SettingNumber": 2,
      "ServerTag": "",
      "ServerPlayerTag": ":",
      "PlayerChatTag": ":",
      "ChatTag": "",
      "HideNameTag": false,
      "DiscordChannelId": 0
    }
  ],

  "PrefixGroups": [
    {
      "ChatPrefix": "/prefix",
      "ServerList": [
        "chat1",
        "chat2"
      ]
    },
    {
      "ChatPrefix": "/prefix2",
      "ServerList": [
        "chat1",
        "chat2"
      ]
    }
  ],

  "Tribes": [
    {
      "TribeId": "00000",
      "SettingToUse": 1,
      "Active": false
    },
    {
      "TribeId": "00000",
      "SettingToUse": 2,
      "Active": false
    }
  ],

  "TribeSettings": [
    {
      "SettingNumber": 1,
      "ShowFullTribeLog": false,
      "ShowTribeName": false,
      "ShowServerName": true,
      "ShowTribeId": true,
      "EmbedTribeLog": true,
      "DiscordChannelId": 1192284714120261712
    },
    {
      "SettingNumber": 2,
      "ShowFullTribeLog": false,
      "ShowTribeName": false,
      "ShowServerName": true,
      "ShowTribeId": false,
      "EmbedTribeLog": true,
      "DiscordChannelId": 0
    }
  ],

  "GameCommands": [
    {
      "Command": "!discord",
      "CommandReply": "https://discord.gg/hQVT2Gh4TR",
      "Active": true
    },
    {
      "Command": "!rules",
      "CommandReply": "These are the rules.",
      "Active": false
    },
    {
      "Command": "!ing",
      "CommandReply": "Pong!",
      "Active": false
    }
  ],

  "CustomTagList": [
    "ACM[CMD]",
    "SERVER: ACM[CMD]"
  ],

  "RconSettings": {
    "NoResponceTag": "Server received, But no response!!",
    "NoPlayerTag": "No Players Connected",
    "ServerRepeatTag": "SERVER:",
    "AdminCMDTag": "AdminCmd:",
    "TribeLogTag": "Tribe",
    "GetChatCmd": "getchat",
    "ListPlayersCmd": "ListPlayers",
    "ListPlayerCheckTimeInMs": 10000,
    "GetChatTimeInMs": 1000,
    "PlayerCountCheckTimeInMs": 30000,
    "VersionCheckTimeInMs": 3600000,
    "RconSendTimeoutInMs": 3000,
    "RconReceiveTimeoutInMs": 10000,
    "RconConnectionRetrys": 1
  },

  "EmbeddedTribeLogColorSettings": [
    {
      "LogType": "killed",
      "LogColor": "ff2121",
      "RoleToPing": "none"
    },
    {
      "LogType": "demolished",
      "LogColor": "ff2121",
      "RoleToPing": "none"
    },
    {
      "LogType": "claimed",
      "LogColor": "03f413",
      "RoleToPing": "none"
    },
    {
      "LogType": "unclaimed",
      "LogColor": "ff2121",
      "RoleToPing": "none"
    },
    {
      "LogType": "tamed",
      "LogColor": "03f413",
      "RoleToPing": "none"
    },
    {
      "LogType": "destroyed",
      "LogColor": "ff7400",
      "RoleToPing": "none"
    },
    {
      "LogType": "froze",
      "LogColor": "d8ddd8",
      "RoleToPing": "none"
    },
    {
      "LogType": "downloaded",
      "LogColor": "03f413",
      "RoleToPing": "none"
    },
    {
      "LogType": "uploaded",
      "LogColor": "ff2121",
      "RoleToPing": "none"
    },
    {
      "LogType": "starved",
      "LogColor": "ff2121",
      "RoleToPing": "none"
    }
  ],

  "ChatSettings": {
    "UseCustomTags": false,
    "SendChatToServers": true,
    "ShowAdminCommands": true,
    "UseGameCommands": true,
    "UsePrefixToSendChat": false,
    "UseWordReplacementList": false,
    "AllServersChatPrefix": "/all"
  },

  "DiscordSettings": {
    "DiscordBotSettings": {
      "CommandPrefix": "d!",
      "DiscordBotToken": "xxxxxxxxxxxxxxxxxx",
      "IgnoreOtherBots": false,
      "ShowDiscordNickName": true
    },

    "ServerChatSettings": {
      "ChatDiscordChannelID": 1192284714120261712,
      "SendServerChatToOwnChannel": false
    },

    "DiscordChatSettings": {
      "DiscordChatPrefix": "Discord",
      "SendChatToDiscord": true,
      "UsePrefixToSendToDiscord": true,
      "PrefixToSendToDiscord": "/discord"
    },

    "NotificationSettings": {
      "VersionDiscordChannelId": 1192284714120261712,
      "PatchNotesDiscordChannelId": 1192284714120261712,
      "JoinLeaveNotificationsDiscordChannelID": 1192284714120261712,
      "UseVersionChecker": true,
      "UsePatchNotesChecker": true,
      "UseJoinLeaveNotifications": true,
      "UsePlayerCountChannelUpdater": true,
      "SendJoinLeaveNotificationsToServerOwnChannel": true
    },

    "AdminCommandSettings": {
      "AdminCommandsDiscordChannelID": 1189725983461351525,
      "SendAdminCommandsToOwnChannel": true
    },

    "TribeLogSettings": {
      "TribeLogsDiscordChannelID": 1192284714120261712,
      "ShowTribelogs": false,
      "ShowFullTribeLog": false,
      "ShowTribeId": true,
      "ShowTribeName": true,
      "ShowServerName": true,
      "EmbedTribeLog": true,
      "SendTribeLogsToOwnChannel": false
    },

    "SupportSettings": {
      "SupportDiscordChannelID": 1192284714120261712,
      "UseSupportPrefix": false,
      "PingRoleName": false,
      "ReplyToSupportPing": true,
      "SupportPrefix": "/help",
      "SupportRoleToPing": "rolename",
      "SupportPingReply": "Your support ticket has been sent."
    }
  }
}

**Comment by spikeydragoon** [comment]
@adler234639  I was attempting to remove your bot token but it looks like you were doing that at the same time. Please make sure to generate a new token just in case someone else saw that token since its dangerous to share that token.

To fix is issue you just have to enable a setting discord requires.


Copied from discord server.
Just an update for those that have not seen the support channel.

Discord changed a few requirements for bots now so if your commands are no longer working make sure to enable message intents. You do this in the discord developer portal under the bot tab for the bot account you created.
![image](https://github.com/spikeydragoon/Cross-Ark-Chat/assets/29191122/6a2c1d45-21f9-41c9-966d-04a08c0bdd27)
You can select the other two intents as well for faster role updates when changing the discordroles.json file but they are not required.
