### ISSUE TITLE
cant send message from cluster to discord

### ISSUE THREAD

**Issue by tmzasz** [spikeydragoon/Cross-Ark-Chat#82]
so i am able to get server to server and discord to cluster working but server to discord fails with this in the rcon error log
11:18:45 Object reference not set to an instance of an object.

**Comment by tmzasz** [comment]
further information the server is ubuntu 22.04 using the latest release of cac
contents of the DiscordLogs.txt file
11:05:39 [Info] Discord: Discord.Net v2.2.0 (API v6)
11:05:40 [Info] Gateway: Connecting
11:05:40 [Info] Gateway: Connected
11:05:41 [Info] Gateway: Ready
11:06:10 [Warning] Gateway: Unknown Dispatch (INTEGRATION_UPDATE)

Configuration file attached ( info redacted but matches bot token and ip/password of server and bot has all 3 intents activated )


[_configuration.json](https://github.com/spikeydragoon/Cross-Ark-Chat/files/14016455/_configuration.json)

**Comment by spikeydragoon** [comment]
Name tag is the issue currently it has a bug that does not all spaces.

So remove the space or replace it with _ or - ect.
Example
TheIsland
The-Island
The_Island

note that just nicknames for the server so you can call it something else or shorten it if you want.

**Comment by tmzasz** [comment]
that worked! ty :)

**Comment by spikeydragoon** [comment]
np
