### ISSUE TITLE
Message Formatting/Options?

### ISSUE THREAD

**Issue by EasyGoinGaming** [spikeydragoon/Cross-Ark-Chat#84]
Hello Spikey - Great tool you've made here. This is less of an issue, and maybe more of a suggestion. The tool works brilliantly, but the usage of the generic ServerChat command make the messages themselves, a bit ugly unfortunately.

Do you think there is any chance you would consider making an optional integration to utilize either RCONExtended commands, or Advanced Messages commands? These plugins both provide new RCON capability to send messages that are formatted like typical server chat - and Advanced Messages even offers some coloring options for the message (if ya wanted to get real fancy)

**Comment by EasyGoinGaming** [comment]
Hopefully not a bother, figured I'd reference those plugin's instructions;

Advanced Messages;
```
Console/RCON Commands:
(If steam id is 0 it will be sent to everyone online, r g b parameters are optional, if they are not written color will be taken from config defaults)

    am.sendchat <steam id> <message sender>"Message" <r> <g> <b> - Sends a client chat message to all online players.
    am.sendserver <steam id> "Message" <r> <g> <b> - Sends a server chat message to all online players
    am.sendnotification <steam id> "Message" <display scale> <display time> <r> <g> <b> <icon bp path> - Sends a notification message to all online players. Icon bp is optional, path is in format of /Game/PrimalEarth/CoreBlueprints/Items/Armor/Mammoth/Icons/MammothLegs_Icon.MammothLegs_Icon
    am.chatasplayer <steam id> "Message to send as player". This will force the player to send a chat message, it can be a command too like /shop. Player needs to be online.
    am.reload - Reloads the config file

I think this would be the best option to use. With <steam id> 0 it is sent server wide, and the R/G/B is purely optional in the plugin as well and can be ignored for simplicity.
am.sendchat <steam id> <message sender>"Message" <r> <g> <b>
```

Extended RCON:
```
[12/18/2024 10:53 AM] > SendMessageToChat
[12/18/2024 10:53 AM] Not enough arguments: <'Message'> <Sender>
[12/18/2024 10:54 AM] > sendmessagetochat 'Testing something else' Davoguha
```

**Comment by spikeydragoon** [comment]
Yes I do have plans to allow the command that is used for chat to be swapped and at some point make my own integration as well. I will be keeping the default as server chat though so it maintains the highest support since not all systems support plugins.

No eta on feature at this time.
